PAIRINGS_IN_C: src/gss/sdh_zk.c File Reference
sdh_zk.c File Reference
#include "gss/sdh_zk.h"
#include "bigint/bi.h"
#include "fp/fp.h"
#include "ec/ec.h"
#include "fp/fp12.h"
#include "pbc/pbc.h"
#include "hash/hashing.h"
#include "hash/hash_function.h"
Functions
void sgs_init (length_t number_of_members, group_public_key *gpk, group_master_secret_key *gmsk, group_secret_key *gsk)
Generates the keys according to the scheme of short group signature by BBS.
void sgs_sign (group_public_key gpk, group_secret_key gsk, sdh_signiture *sig, const char *message)
Generates a signature according to the scheme of short group signature by BBS.
sbyte sgs_verify (group_public_key gpk, sdh_signiture sig, const char *message)
Verifies a signature according to the scheme of short group signatureb by BBS.
void sgs_open (group_master_secret_key gmsk, sdh_signiture sig, ecpoint_fp *A)
Trace a signature to a signer.
Function Documentation
void sgs_init (length_t number_of_members, group_public_key * gpk, group_master_secret_key * gmsk, group_secret_key * gsk)
Generates the keys according to the scheme of short group signature by BBS.
Parameters
number_of_members [in] number of secret keys that should be generated.
gpk [out] public key of sgs scheme.
gsk [out] different user secret keys to generate a valid signatures.
gmsk [out] group master secret key to trace a valid signature.
Definition at line 54 of file sdh_zk.c.
References cprng_get_bytes(), ecfp2_copy_std(), and ecfp_copy_std().
Referenced by main().
void sgs_open (group_master_secret_key gmsk, sdh_signiture sig, ecpoint_fp * A)
Trace a signature to a signer.
Parameters
gmsk [in] group master secret key to trace a valid signature.
sig [in] computed signature.
A [in] part of user secret key.
Definition at line 407 of file sdh_zk.c.
Referenced by main().
void sgs_sign (group_public_key gpk, group_secret_key gsk, sdh_signiture * sig, const char * message)
Generates a signature according to the scheme of short group signature by BBS.
Parameters
gpk [in] public key of sgs scheme.
gsk [in] user secret key to generate a valid signature.
sig [out] computed signature.
message [in] the message for signature generation .
Definition at line 129 of file sdh_zk.c.
References bi_clear_var_std(), bi_copy_var_std(), cprng_get_bytes(), hash_update_G1(), hash_update_GT(), and hash_update_message().
Referenced by main().
sbyte sgs_verify (group_public_key gpk, sdh_signiture sig, const char * message)
Verifies a signature according to the scheme of short group signatureb by BBS.
Parameters
gpk [in] public key of sgs scheme.
sig [in] computed signature.
message [in] the message for signature generation .
Returns
0 on valid signature; -1 on invalid signature;
Definition at line 294 of file sdh_zk.c.
References bi_clear_var_std(), bi_copy_var_std(), fp12_mul_std(), hash_update_G1(), hash_update_GT(), and hash_update_message().
Referenced by main().