PAIRINGS_IN_C: src/hash/hashing.c File Reference
hashing.c File Reference
#include "hash/hash_function.h"
#include "types.h"
#include <string.h>
Functions
void hash_key (byte *res, fp12_t key)
Hash a fp12_t element to a 128-bit key.
void hash_id (bigint_t res, char *id)
Hash a an identity string to a big integer.
void hash_update_message (hashState *state, const char *message)
Updates the given Hash state with the given message.
void hash_update_G1 (hashState *state, const ecfp_pt g1)
Updates the given Hash state with the given element in {G}_1.
void hash_update_GT (hashState *state, const fp12_t gt)
Updates the given Hash state with the given element in {G}_T.
Function Documentation
void hash_id (bigint_t res, char * id)
Hash a an identity string to a big integer.
Parameters
res the resulting big integer
id the identity string of arbitrary length
Definition at line 59 of file hashing.c.
Referenced by derive_private_key(), encapsulate_key(), and main().
void hash_key (byte * res, fp12_t key)
Hash a fp12_t element to a 128-bit key.
The user must ensure that the array represented by res is of appropriate size.
Parameters
res the resulting 128-bit key
key the element to be hashed
Definition at line 46 of file hashing.c.
Referenced by decapsulate_key(), and encapsulate_key().
void hash_update_G1 (hashState * state, const ecfp_pt g1)
Updates the given Hash state with the given element in {G}_1.
Parameters
state the Hash state to be used.
g1 the elliptic curve point to be hashed.
Definition at line 98 of file hashing.c.
References print_value().
Referenced by hwang_sign(), hwang_verify(), sgs_sign(), and sgs_verify().
void hash_update_GT (hashState * state, const fp12_t gt)
Updates the given Hash state with the given element in {G}_T.
Parameters
state the Hash state to be used.
g1 the 12th extension field to be hashed.
Definition at line 133 of file hashing.c.
Referenced by hwang_sign(), hwang_verify(), sgs_sign(), and sgs_verify().
void hash_update_message (hashState * state, const char * message)
Updates the given Hash state with the given message.
Parameters
state the Hash state to be used.
message the message to be hashed.
Definition at line 70 of file hashing.c.
Referenced by sgs_sign(), and sgs_verify().