PAIRINGS_IN_C: src/base/std/fp/fp.c File Reference
fp.c File Reference
#include "fp/fp.h"
#include "bigint/bi.h"
Functions
void fp_add_std (fp_t res, const fp_t a, const fp_t b, const bigint_t mod)
Adds two prime field elements.
void fp_add_lazy (fp_t res, const fp_t a, const fp_t b, const bigint_t mod, const bigint_t multipleMod)
Adds two prime field elements using lazy reduction, ie.
void fp_dbl_std (fp_t res, const fp_t a, const bigint_t mod)
Doubles a prime field element.
void fp_sub_std (fp_t res, const fp_t a, const fp_t b, const bigint_t mod)
Subtracts two prime field elements.
void fp_sub_lazy (fp_t res, const fp_t a, const fp_t b, const bigint_t mod, const bigint_t multipleMod)
Subtracts two prime field elements using lazy reduction, ie.
void fp_neg_std (fp_t res, const fp_t a, const bigint_t mod)
Negates a prime field element.
void fp_neg_lazy (fp_t res, const fp_t a, const bigint_t mod, const bigint_t multipleMod)
Negates a prime field element using lazy reduction.
void fp_mul_std (fp_t res, const fp_t a, const fp_t b, const bigint_t mod, const bigint_t mu)
Multiplies to prime field elements in two separate steps: multiplication and barrett reduction.
void fp_hlv_std (fp_t res, const fp_t a, const bigint_t mod)
Halves a prime field element.
void fp_rdc_monty_lazy (fp_t res, word_t *t, const bigint_t mod, const word_t n0, const bigint_t multipleMod)
Montgomery reduction using lazy reduction, ie.
void fp_rdc_monty_std (fp_t res, word_t *t, const bigint_t mod, const word_t n0)
A montgomery reduction routine.
void fp_mul_monty_twostep_lazy (fp_t res, const fp_t a, const fp_t b, const bigint_t modulo, const word_t n0, const bigint_t multipleMod)
Montgomery prime field multiplication using lazy reduction.
void fp_mul_monty_twostep (fp_t res, const fp_t a, const fp_t b, const bigint_t modulo, const word_t n0)
Montgomery prime field multiplication that is separated into a bigint multiplication and a reduction step.
void fp_mul_monty_fips_std (fp_t res, const fp_t a, const fp_t b, const bigint_t n, const word_t n0)
The montgomery multiplication in its FIPS (Finely Integrated Product Scanning) variant.
void fp_mul_monty_std (fp_t res, const fp_t a, const fp_t b, const bigint_t modulo, const bigint_t n0)
Simple and straight forward Montgomery multiplication.
void fp_exp_monty (fp_t res, const fp_t a, const bigint_t b, const bigint_t modulo, const bigint_t n0, const bigint_t r2)
Prime field exponentation that converts the operands into the Montgomery domain and converts the result back.
void fp_inv_exp_var_std (fp_t res, const fp_t a, const bigint_t mod, const bigint_t mu_n)
Prime field inversion by exponentiation using Little Fermat.
void fp_inv_exp_std (fp_t res, const fp_t a)
Prime field inversion by exponentation using Little Fermat using the default prime and a precomputed exponent.
void fp_exp_bn (fp_t res, const fp_t a, const bigint_t exp)
Simple square and multiply exponentiation that uses branches and may only be used for known exponents (SCA leakage!).
void fp_inv_bn (fp_t res, const fp_t a)
Special inversion algorithm valid for BN curves.
void fp_exp_sqrmul (fp_t res, const fp_t a, const bigint_t b, const bigint_t mod, const bigint_t mu)
Square-and-Multiply prime field exponentiation with side-channel dummy (but not SCA secure (use Montgomery ladder instead)).
void fp_exp_std (fp_t res, const fp_t a, const bigint_t b, const bigint_t mod, const bigint_t mu)
Prime field exponentiation (but not SCA secure (use Montgomery ladder instead)).
void fp_sqrt_std (fp_t res, const fp_t a, const bigint_t mod, const bigint_t mu)
Prime field square root computation.
int fp_legendre_std (const fp_t a, const bigint_t mod, const bigint_t mu)
Legendre operation in the prime field, ie.
void fp_rdc_std (fp_t a, const bigint_t mod)
void fp_rdc_2l_std (word_t *a, const bigint_t mod, const word_t *mu)
Performs a modular reduction (Barrett reduction) on a big integer that is twice the normal size.
void fp_clear_std (fp_t a)
Clears the prime field value.
void fp_copy_std (fp_t a, const fp_t b)
Copies the prime field element.
void fp_to_montgomery_std (fp_t res, const fp_t a)
Transforms a prime field value into montgomery domain.
void fp_from_montgomery_std (fp_t res, const fp_t a)
Transform a prime field value in montgomery domain back.
Function Documentation
void fp_add_lazy (fp_t res, const fp_t a, const fp_t b, const bigint_t mod, const bigint_t multipleMod)
Adds two prime field elements using lazy reduction, ie.
it subtracts the prime only if an overflow occurs.
Parameters
res the sum
a the first operand
b the second operand
mod the prime (modulus)
multipleMod a multiple of the modulus that, if an overflow occurs, can be subtracted at once if the prime has leading zeros
Definition at line 64 of file fp.c.
void fp_add_std (fp_t res, const fp_t a, const fp_t b, const bigint_t mod)
Adds two prime field elements.
Parameters
res the sum
a the first operand
b the second operand
mod the prime (modulus)
Definition at line 45 of file fp.c.
void fp_clear_std (fp_t a)
Clears the prime field value.
Parameters
a the prime field element
Definition at line 829 of file fp.c.
void fp_copy_std (fp_t a, const fp_t b)
Copies the prime field element.
Parameters
a the destination
b the source
Definition at line 838 of file fp.c.
void fp_dbl_std (fp_t res, const fp_t a, const bigint_t mod)
Doubles a prime field element.
Parameters
res the doubled result
a the operand
mod the prime (modulus)
Definition at line 80 of file fp.c.
void fp_exp_bn (fp_t res, const fp_t a, const bigint_t exp)
Simple square and multiply exponentiation that uses branches and may only be used for known exponents (SCA leakage!).
Parameters
res the result
a the operand
exp the exponent
Definition at line 510 of file fp.c.
Referenced by fp_inv_bn().
void fp_exp_monty (fp_t res, const fp_t a, const bigint_t b, const bigint_t modulo, const bigint_t n0, const bigint_t r2)
Prime field exponentation that converts the operands into the Montgomery domain and converts the result back.
Parameters
res the result
a the operand
b the exponent
modulo the prime modulus
n0 the precomputed constant for Montgomery reduction
r2 the precomputed constant r^2 for converting into the montgomery domain
Definition at line 424 of file fp.c.
void fp_exp_sqrmul (fp_t res, const fp_t a, const bigint_t b, const bigint_t mod, const bigint_t mu)
Square-and-Multiply prime field exponentiation with side-channel dummy (but not SCA secure (use Montgomery ladder instead)).
Parameters
res the result
a the first operand
b the exponent
mod the prime (modulus)
mu the precomputed constant for the Barrett reduction
Definition at line 710 of file fp.c.
Referenced by fp_exp_std().
void fp_exp_std (fp_t res, const fp_t a, const bigint_t b, const bigint_t mod, const bigint_t mu)
Prime field exponentiation (but not SCA secure (use Montgomery ladder instead)).
Parameters
res the result
a the first operand
b the exponent
mod the prime (modulus)
mu the precomputed constant for the Barrett reduction
Definition at line 737 of file fp.c.
References fp_exp_sqrmul().
void fp_from_montgomery_std (fp_t res, const fp_t a)
Transform a prime field value in montgomery domain back.
Parameters
res the result
a the value in montgomery domain
Definition at line 858 of file fp.c.
void fp_hlv_std (fp_t res, const fp_t a, const bigint_t mod)
Halves a prime field element.
Parameters
res the halved value
a the operand
mod the prime (modulus)
Definition at line 175 of file fp.c.
void fp_inv_bn (fp_t res, const fp_t a)
Special inversion algorithm valid for BN curves.
It makes use of the special form of the BN primes to calculate a^(p-2) for side-channel resistant inversion.
Parameters
res the inverse of a
a the value to be inverted
Definition at line 534 of file fp.c.
References fp_exp_bn().
void fp_inv_exp_std (fp_t res, const fp_t a)
Prime field inversion by exponentation using Little Fermat using the default prime and a precomputed exponent.
Parameters
res the result
a the operand
Definition at line 488 of file fp.c.
void fp_inv_exp_var_std (fp_t res, const fp_t a, const bigint_t mod, const bigint_t mu_n)
Prime field inversion by exponentiation using Little Fermat.
Works for any prime modulus.
Parameters
res the resulting inverse
a the operand
mod the prime (modulus)
mu_n the parameter mu for barrett reduction
Definition at line 462 of file fp.c.
int fp_legendre_std (const fp_t a, const bigint_t mod, const bigint_t mu)
Legendre operation in the prime field, ie.
it determines whether the operand is a square or not.
Parameters
a the operand
mod the prime modulus
mu the precomputed constnat for the Barrett reduction
Returns
1 if square, -1 if not, 0 if zero
Definition at line 763 of file fp.c.
void fp_mul_monty_fips_std (fp_t res, const fp_t a, const fp_t b, const bigint_t n, const word_t n0)
The montgomery multiplication in its FIPS (Finely Integrated Product Scanning) variant.
Warning: This one is rather slow in pure C - in assembler it can be nicely optimized.
Parameters
res the resulting product
a the first operand
b the second operand
n the modulus (prime)
n0 the precomputed constant for montgomery reduction
Definition at line 326 of file fp.c.
Referenced by main().
void fp_mul_monty_std (fp_t res, const fp_t a, const fp_t b, const bigint_t modulo, const bigint_t n0)
Simple and straight forward Montgomery multiplication.
Don't expect speed records...
Parameters
res the resulting product
a the first operand
b the second operand
modulo the prime (modulus)
n0 the precomputed constant for montgomery reduction
Definition at line 378 of file fp.c.
Referenced by main().
void fp_mul_monty_twostep (fp_t res, const fp_t a, const fp_t b, const bigint_t modulo, const word_t n0)
Montgomery prime field multiplication that is separated into a bigint multiplication and a reduction step.
Parameters
res the resulting product
a the first operand
b the second operand
modulo the prime (modulus)
n0 the precomputed constant for montomgery reduction
Definition at line 310 of file fp.c.
void fp_mul_monty_twostep_lazy (fp_t res, const fp_t a, const fp_t b, const bigint_t modulo, const word_t n0, const bigint_t multipleMod)
Montgomery prime field multiplication using lazy reduction.
It is separated into a bigint multiplication and a reduction step.
Parameters
res the product
a the first operand
b the second operand
modulo the prime (modulus)
n0 the precomputed constant for montgomery reduction
multipleMod a multiple of the modulus for reduction
Definition at line 295 of file fp.c.
References fp_rdc_monty_lazy().
void fp_mul_std (fp_t res, const fp_t a, const fp_t b, const bigint_t mod, const bigint_t mu)
Multiplies to prime field elements in two separate steps: multiplication and barrett reduction.
Parameters
res the product
a the first operand
b the second operand
mod the prime (modulus)
mu parameter mu for barrett reduction
Definition at line 160 of file fp.c.
void fp_neg_lazy (fp_t res, const fp_t a, const bigint_t mod, const bigint_t multipleMod)
Negates a prime field element using lazy reduction.
Parameters
res the negated element
a the operand
mod the prime (modulus)
multipleMod a multiple of the modulus that is used to "mirror" the operand
Definition at line 143 of file fp.c.
void fp_neg_std (fp_t res, const fp_t a, const bigint_t mod)
Negates a prime field element.
Parameters
res the negated element
a the operand
mod the prime (modulus)
Definition at line 129 of file fp.c.
void fp_rdc_2l_std (word_t * a, const bigint_t mod, const word_t * mu)
Performs a modular reduction (Barrett reduction) on a big integer that is twice the normal size.
Parameters
a the value to be reduced
mod the prime (modulus)
mu the constant for Barrett reduction
Definition at line 798 of file fp.c.
void fp_rdc_monty_lazy (fp_t res, word_t * t, const bigint_t mod, const word_t n0, const bigint_t multipleMod)
Montgomery reduction using lazy reduction, ie.
the final reduction step is performed using lazy reduction.
Parameters
res the reduced result
t the operand to be reduced (length: 2*BI_WORDS)
mod the prime (modulus)
n0 the precomputed value n0 of the montgomery reduction
multipleMod a multiple of the modulus that may be subtracted at once in the final reduction step if the prime has leading zeros
Definition at line 196 of file fp.c.
Referenced by fp_mul_monty_twostep_lazy().
void fp_rdc_monty_std (fp_t res, word_t * t, const bigint_t mod, const word_t n0)
A montgomery reduction routine.
Parameters
res the reduced result
t the operand to be reduced (length: 2*BI_WORDS)
mod the prime (modulus)
n0 the precomputed value n0 of the montgomery reduction
Definition at line 236 of file fp.c.
void fp_rdc_std (fp_t a, const bigint_t mod)
Definition at line 787 of file fp.c.
void fp_sqrt_std (fp_t res, const fp_t a, const bigint_t mod, const bigint_t mu)
Prime field square root computation.
Parameters
res the result
a the operand
mod the prime (modulus)
mu the precomputed constant for the Barrett reduction
Definition at line 748 of file fp.c.
void fp_sub_lazy (fp_t res, const fp_t a, const fp_t b, const bigint_t mod, const bigint_t multipleMod)
Subtracts two prime field elements using lazy reduction, ie.
it adds the prime only if an underflow occurs.
Parameters
res the difference
a the first operand
b the second operand that is subtracted
mod the prime (modulus)
multipleMod a multiple of the modulus that, if an underflow occurs, can be added at once if the prime has leading zeros
Definition at line 115 of file fp.c.
void fp_sub_std (fp_t res, const fp_t a, const fp_t b, const bigint_t mod)
Subtracts two prime field elements.
Parameters
res the difference
a the first operand
b the second operand that is subtracted
mod the prime (modulus)
Definition at line 99 of file fp.c.
void fp_to_montgomery_std (fp_t res, const fp_t a)
Transforms a prime field value into montgomery domain.
Parameters
res the result
a the orignal value
Definition at line 847 of file fp.c.