Pairings: /home/work/workspace/bipair_in_c/src/assert.c File Reference
assert.c File Reference
#include "util.h"
#include "bigint/bi.h"
Functions
int assert_true (const int c, const char *msg)
Verifies that the parameter is not equal zero (= true)
int assert_bytearr_equal (const byte *ex, const byte *tst, const length_t length, const char *msg)
Verifies that two byte arrays are equal.
int assert_bi_equal (const bigint_t ex, const bigint_t tst, const char *msg)
Verifies that two big integers are equal.
int assert_bi_equal_var (const word_t *ex, const word_t *tst, const length_t len, const char *msg)
Verifies that two big integers of defined length are equal.
int assert_equal (word_t ex, word_t tst, const char *msg)
Verifies that two processor words are equal.
Function Documentation
int assert_bi_equal (const bigint_t ex, const bigint_t tst, const char * msg)
Verifies that two big integers are equal.
Parameters
ex the expected big integer
tst the tested big integer
msg the message to be printed
Returns
0 if successful, 1 on failure
Definition at line 86 of file assert.c.
References bi_compare, BI_WORDS, bi_xor, print(), and print_value().
Referenced by main().
int assert_bi_equal_var (const word_t * ex, const word_t * tst, const length_t len, const char * msg)
Verifies that two big integers of defined length are equal.
Parameters
ex the expected big integer
tst the tested big integer
len the length of the two big integers
msg the message to be printed
Returns
0 if successful, 1 otherwise
Definition at line 114 of file assert.c.
References bi_compare_var, bi_xor_var, print(), and print_value().
Referenced by main().
int assert_bytearr_equal (const byte * ex, const byte * tst, const length_t length, const char * msg)
Verifies that two byte arrays are equal.
Parameters
ex the expected array
tst the tested array
length the length of the two arrays
msg the message to be printed
Returns
0 if successful, 1 on failure
Definition at line 64 of file assert.c.
References compare_bytes(), print(), and print_bytes().
Referenced by main().
int assert_equal (word_t ex, word_t tst, const char * msg)
Verifies that two processor words are equal.
Parameters
ex the expected word
tst the tested word
msg the message to be printed
Returns
0 if successful, 1 otherwise
Definition at line 141 of file assert.c.
References print(), and print_value().
Referenced by main().
int assert_true (const int c, const char * msg)
Verifies that the parameter is not equal zero (= true)
Parameters
c the parameter that is checked to be true
msg the message to be printed
Returns
0 if the parameter is true, 1 otherwise
Definition at line 44 of file assert.c.
References print().
Referenced by main().