Pairings: /home/work/workspace/bipair_in_c/include/ibe/bbkem.h File Reference
bbkem.h File Reference
#include "types.h"
Data Structures
struct bbkem_ciphertext
struct bbkem_public
struct bbkem_pk
Functions
void encapsulate_key (byte *key, bbkem_ciphertext *cipher, const char *id)
Generates and encapsulates a 128-bit key based on the BB1-KEM scheme as proposed in the IEEE P1363.3 draft standard.
void decapsulate_key (byte *key, bbkem_ciphertext *cipher, const char *id)
Decapsulates the key that is contained by the ciphertext.
Function Documentation
void decapsulate_key (byte * key, bbkem_ciphertext * cipher, const char * id)
Decapsulates the key that is contained by the ciphertext.
This process is based on the BB1-KEm as proposed in the IEEE P1363.3 draft standard. The key is associated with the given identity.
Parameters
key [out] the decapsulated key
cipher [in] ciphertext that encapsulates the key
id [in] the id of the party that the cipher is destined for
Decapsulates the key that is contained by the ciphertext.
Takes the identity's private key and the received ciphertext to compute the session key to be used. Note that the current implementation does not use the identity string, but always takes the same private key.
Parameters
key the resulting session key
cipher the ciphertext to be decrypted
id the identity string used
Definition at line 102 of file bbkem.c.
References bbkem_ciphertext::c0, bbkem_ciphertext::c1, bbkem_pk::d0, bbkem_pk::d1, ecfp_neg_affine, ecfp_to_montgomery, fp12_from_montgomery, fp12_rdc, hash_key(), pbc_map_opt_ate_div, and pbc_map_opt_ate_mul.
Referenced by main().
void encapsulate_key (byte * key, bbkem_ciphertext * cipher, const char * id)
Generates and encapsulates a 128-bit key based on the BB1-KEM scheme as proposed in the IEEE P1363.3 draft standard.
Parameters
key [out] the key that is generated during this routine (128-bit)
cipher [out] ciphertext that encapsulates the key
id [in] id of the party that the cipher is destined for
Generates and encapsulates a 128-bit key based on the BB1-KEM scheme as proposed in the IEEE P1363.3 draft standard.
Uses the recipient's identity string to establish a session key and a ciphertext decryptable only by the intended recipient.
Parameters
key the resulting session key
cipher the resulting ciphertext
id the identity string of the recipient
Definition at line 56 of file bbkem.c.
References BI_BYTES, bbkem_ciphertext::c0, bbkem_ciphertext::c1, cprng_get_bytes(), EC_PARAM_MU_N, EC_PARAM_N, ecfp_add_affine, ecfp_from_montgomery, ecfp_mul, fp12_exp_cyclotomic, fp12_from_montgomery, fp12_rdc, fp_mul_barett_var, fp_rdc_n, bbkem_public::g, bbkem_public::g1, bbkem_public::g3, hash_id(), hash_key(), and bbkem_public::v0.
Referenced by main().