Pairings: /home/work/workspace/bipair_in_c/include/bench_util.h File Reference
bench_util.h File Reference
#include "config.h"
Typedefs
typedef unsigned long long bm_time_t
Functions
void benchmark_start ()
Start a benchmark.
void benchmark_stop ()
Stop a benchmark.
void benchmark_compute (int iterations)
Compute the mean of all benchmarks for a given count of iterations.
void benchmark_compute_single ()
Computes the result of the previously executed benchmark.
void benchmark_print (const char *msg)
Print the result of the recent benchmark.
Typedef Documentation
typedef unsigned long long bm_time_t
Definition at line 41 of file bench_util.h.
Function Documentation
void benchmark_compute (int iterations)
Compute the mean of all benchmarks for a given count of iterations.
Parameters
iterations the number of benchmark iterations
Definition at line 75 of file bench_util.c.
References BENCH_OVERHEAD, bm_result, bm_start, and bm_stop.
void benchmark_compute_single ()
Computes the result of the previously executed benchmark.
Definition at line 88 of file bench_util.c.
References BENCH_OVERHEAD, bm_result, bm_start, and bm_stop.
void benchmark_print (const char * msg)
Print the result of the recent benchmark.
Parameters
msg a message to be additionally printed
Definition at line 101 of file bench_util.c.
References bm_result, and print().
void benchmark_start ()
Start a benchmark.
Definition at line 52 of file bench_util.c.
References bm_start, and get_cycles().
void benchmark_stop ()
Stop a benchmark.
Definition at line 63 of file bench_util.c.
References bm_stop, and get_cycles().