Pairings: /home/work/workspace/bipair_in_c/include/bigint/bi_std.h File Reference
bi_std.h File Reference
#include "types.h"
Functions
int bi_add_var_std (word_t *res, const word_t *a, const word_t *b, const length_t length)
Adds two big integers of specified length, i.e.
int bi_add_carry_var_std (word_t *res, const word_t *a, const word_t *b, const int carry, const length_t length)
Adds two big integers of specified length and an additional carry, i.e.
int bi_add_word_var_std (word_t *res, const word_t *a, const word_t b, const length_t length)
Adds a single word to an big integer of specified length, i.e.
int bi_subtract_var_std (word_t *res, const word_t *a, const word_t *b, const length_t length)
Subtracts two big integers of specified length, i.e.
int bi_subtract_vl_std (word_t *res, const word_t *a, const word_t *b, const length_t length_a, const length_t length_b)
Subtracts two big integers of different length, i.e.
int bi_subtract_word_var_std (word_t *res, const word_t *a, const word_t b, const length_t length)
Subtracts a single word from an big integer of specified length, i.e.
void bi_clear_var_std (word_t *a, const length_t length)
Sets each element of the big integer to zero.
void bi_xor_var_std (word_t *res, const word_t *a, const word_t *b, const length_t length)
Performs an XOR operation on two big integers, i.e.
void bi_shift_right_var_std (word_t *res, const word_t *a, const uint right, const length_t length)
Shifts an big integer to the right by the specified amount of bits.
void bi_shift_right_one_var_std (word_t *res, const word_t *a, const length_t length)
Shifts a big integer right by one bit.
void bi_shift_left_one_var_std (word_t *res, const word_t *a, const length_t length)
Shifts a big integer left by one bit.
void bi_div3_var_std (word_t *res, const word_t *a, length_t length)
Performs a division by 3.
int bi_compare_var_std (const word_t *a, const word_t *b, const length_t length)
Compares two values, a and b, and returns 0 if equal, 1 if a > b, and -1 otherwise.
int bi_compare_vl_std (const word_t *a, const word_t *b, const length_t length_a, const length_t length_b)
Compares two values, a and b, of different length.
void bi_multiply_var_std (word_t *result, const word_t *a, const word_t *b, const length_t length_a, const length_t length_b)
Multiplies two values a and b, i.e.
void bi_multiply_word_var_std (word_t *result, const word_t *a, const word_t b, const length_t length_a)
Multiplies a big integer with a single word, i.e.
void bi_copy_var_std (word_t *dest, const word_t *source, const length_t length)
Copies a big integer.
void bi_set_bit_var_std (word_t *a, const uint bit, const length_t length)
Sets a single bit in a big integer.
int bi_test_bit_var_std (const word_t *a, const uint bit, const length_t length)
Tests whether a bit is set, i.e.
int bi_get_msb_var_std (const word_t *a, const length_t length)
Returns the index of the most significant bit set.
byte bi_get_byte_var_std (const word_t *a, const length_t length, const uint index)
Returns the byte of the given big integer at the specified index.
void bi_set_byte_var_std (word_t *a, const length_t length, const uint index, const byte value)
Sets the byte of the given big integer at the specified index.
void bi_negate_var_std (word_t *res, const word_t *a, const length_t length)
Negates a big integer.
int bi_get_nafw_std (sbyte *nafw, word_t *a, word_t width)
Returns a w-bit NAF representation of the input, where w is specified by the parameter width.
int bi_get_nafb_std (sbyte *naf, word_t *a)
Returns a binary NAF representation of the input.
Function Documentation
int bi_add_carry_var_std (word_t * res, const word_t * a, const word_t * b, const int cin, const length_t length)
Adds two big integers of specified length and an additional carry, i.e.
res = a + b + cin.
Parameters
res the result (sum) of the addition
a operand a
b operand b
cin carry input
length length of a, b, and res
Returns
carry
Definition at line 145 of file bi.c.
int bi_add_var_std (word_t * res, const word_t * a, const word_t * b, const length_t length)
Adds two big integers of specified length, i.e.
res = a + b.
Parameters
res the result (sum) of the addition
a operand a
b operand b
length length of a, b, and res
Returns
carry
Definition at line 121 of file bi.c.
int bi_add_word_var_std (word_t * res, const word_t * a, const word_t b, const length_t length)
Adds a single word to an big integer of specified length, i.e.
res = a + b.
Parameters
res the result of the addition (big integer)
a operand a (big integer)
b operand b (single word)
length length of a and res
Returns
carry
Definition at line 168 of file bi.c.
void bi_clear_var_std (word_t * a, const length_t length)
Sets each element of the big integer to zero.
Parameters
a the big integer to be reset
length length of a
Definition at line 267 of file bi.c.
Referenced by hwang_sign(), and hwang_verify().
int bi_compare_var_std (const word_t * a, const word_t * b, const length_t length)
Compares two values, a and b, and returns 0 if equal, 1 if a > b, and -1 otherwise.
Parameters
a parameter a
b parameter b
length length of a and b
Returns
0 if equal, 1 if a > b, -1 otherwise
Definition at line 390 of file bi.c.
int bi_compare_vl_std (const word_t * a, const word_t * b, const length_t length_a, const length_t length_b)
Compares two values, a and b, of different length.
Parameters
a parameter a
b parameter b
length_a length of big integer a
length_b length of big integer b
Returns
0 if equal, 1 if a > b, -1 otherwise
Definition at line 412 of file bi.c.
void bi_copy_var_std (word_t * dest, const word_t * source, const length_t length)
Copies a big integer.
Parameters
dest destination
source source
length length of source and destination
Definition at line 481 of file bi.c.
Referenced by hwang_init_parameters(), hwang_sign(), and hwang_verify().
void bi_div3_var_std (word_t * res, const word_t * a, length_t length)
Performs a division by 3.
Parameters
res result of the division
a value to be divided
length length of a and res
Definition at line 325 of file bi.c.
References bi_copy_var, and bi_multiply_var.
byte bi_get_byte_var_std (const word_t * a, const length_t length, const uint index)
Returns the byte of the given big integer at the specified index.
Parameters
a the big integer
length length of a
index the index of the byte to be read
Returns
the byte at the specified index
Definition at line 551 of file bi.c.
References BYTES_PER_WORD, and LD_BYTES_PER_WORD.
int bi_get_msb_var_std (const word_t * a, const length_t length)
Returns the index of the most significant bit set.
Parameters
a parameter where the MSB is to be determined
length length of a
Returns
index of the MSB, -1 if a is 0
Definition at line 527 of file bi.c.
References BITS_PER_WORD.
int bi_get_nafb_std (sbyte * naf, word_t * a)
Returns a binary NAF representation of the input.
Parameters
naf an array for the resulting NAF representation
a the value to be converted into NAF
Returns
the number of elements in the NAF representation
Definition at line 85 of file bi.c.
References bi_compare, bi_is_odd, bi_shift_right_one, bi_zero, and BITS_PER_WORD.
int bi_get_nafw_std (sbyte * nafw, word_t * a, word_t width)
Returns a w-bit NAF representation of the input, where w is specified by the parameter width.
Parameters
nafw an array for the resulting NAF representation
a the value to be converted into NAF
width the NAF-width
Returns
the number of elements in the NAF representation
Definition at line 45 of file bi.c.
References bi_compare, bi_is_odd, bi_shift_right_one, bi_zero, and BITS_PER_WORD.
void bi_multiply_var_std (word_t * result, const word_t * a, const word_t * b, const length_t length_a, const length_t length_b)
Multiplies two values a and b, i.e.
res = a * b. Beware that |res| >= length_a + length_b
Parameters
result the product of a and b
a operand a
b operand b
length_a length of a
length_b length of b
Definition at line 442 of file bi.c.
References bi_clear_var, and BITS_PER_WORD.
void bi_multiply_word_var_std (word_t * result, const word_t * a, const word_t b, const length_t length_a)
Multiplies a big integer with a single word, i.e.
res = a * b. Beware that |res| >= length_a + 1.
Parameters
result the resulting product (big integer)
a parameter a (big integer)
b parameter b (word)
length_a length of big integer a
Definition at line 471 of file bi.c.
References bi_multiply_var.
void bi_negate_var_std (word_t * res, const word_t * a, const length_t length)
Negates a big integer.
Parameters
res the negate of a
a the big integer to be negated
length length of a and res
Definition at line 590 of file bi.c.
References bi_add_var, and bi_one.
void bi_set_bit_var_std (word_t * a, const uint bit, const length_t length)
Sets a single bit in a big integer.
Parameters
a the big integer to be manipulated
bit the number of the bit to be set
length length of a
Definition at line 494 of file bi.c.
References BITS_PER_WORD, and LD_BITS_PER_WORD.
void bi_set_byte_var_std (word_t * a, const length_t length, const uint index, const byte value)
Sets the byte of the given big integer at the specified index.
Parameters
a the big integer
length lenght of a
index the index of the byte to be written
value the value to be written at the specified index
Definition at line 571 of file bi.c.
References BYTES_PER_WORD, and LD_BYTES_PER_WORD.
void bi_shift_left_one_var_std (word_t * res, const word_t * a, const length_t length)
Shifts a big integer left by one bit.
Parameters
res the result of the shift operation
a the value to be shifted
length length of a and res
Definition at line 373 of file bi.c.
References BITS_PER_WORD.
void bi_shift_right_one_var_std (word_t * res, const word_t * a, const length_t length)
Shifts a big integer right by one bit.
Parameters
res the result of the shift operation
a the value to be shifted
length length of a and res
Definition at line 357 of file bi.c.
References BITS_PER_WORD.
void bi_shift_right_var_std (word_t * res, const word_t * a, const uint right, const length_t length)
Shifts an big integer to the right by the specified amount of bits.
Parameters
res the result of the shift operation
a the value to be shifted
right number of bits to shift
length length of a and res
Definition at line 295 of file bi.c.
References BITS_PER_WORD, and LD_BITS_PER_WORD.
int bi_subtract_var_std (word_t * res, const word_t * a, const word_t * b, const length_t length)
Subtracts two big integers of specified length, i.e.
res = a - b.
Parameters
res the result (difference) of the subtraction
a operand a
b operand b
length length of a, b, and res
Returns
carry
Definition at line 192 of file bi.c.
int bi_subtract_vl_std (word_t * res, const word_t * a, const word_t * b, const length_t length_a, const length_t length_b)
Subtracts two big integers of different length, i.e.
res = a - b. Beware that |res| >= MAX(length_a, length_b)
Parameters
res the result of the subtraction
a operand a
b operand b
length_a length of a
length_b lenght of b
Returns
Definition at line 217 of file bi.c.
int bi_subtract_word_var_std (word_t * res, const word_t * a, const word_t b, const length_t length)
Subtracts a single word from an big integer of specified length, i.e.
res = a - b.
Parameters
res the result of the subtraction (big integer)
a operand a (big integer)
b operand b (single word)
length length of a and res
Returns
carry
Definition at line 246 of file bi.c.
int bi_test_bit_var_std (const word_t * a, const uint bit, const length_t length)
Tests whether a bit is set, i.e.
returns 1 if the specified bit is set, 0 otherwise.
Parameters
a big integer that is to be tested
bit number of the bit to be tested
length length of parameter a
Returns
1 if set, 0 otherwise
Definition at line 511 of file bi.c.
References BITS_PER_WORD, and LD_BITS_PER_WORD.
void bi_xor_var_std (word_t * res, const word_t * a, const word_t * b, const length_t length)
Performs an XOR operation on two big integers, i.e.
res = a XOR b.
Parameters
res the result
a operand a
b operand b
length length of a, b, and res
Definition at line 281 of file bi.c.