Pairings: /home/work/workspace/bipair_in_c/src/base/std/ec/ecfp.c File Reference
ecfp.c File Reference
#include "ec/ec.h"
#include "fp/fp.h"
#include "bigint/bi.h"
#include "param.h"
Functions
void ecfp_add_dbl_coz_std (fp_t x1, fp_t x2, fp_t z, const fp_t x_d)
Performs a mixed add and double operation in co-Z coordinates to be used in a specialize Montgomery ladder implementation of the elliptic curve point multiplication.
void ecfp_recover_full_coord_coz_std (fp_t x1, fp_t x2, fp_t z, const fp_t x_d, const fp_t y_d)
Recovers the coordinates of the result of the Montgomery ladder elliptic curve point multiplication using co-Z coordinates.
int ecfp_verify_coordinates (fp_t x, fp_t y)
int ecfp_verify_homogeneous_projective_coordinates (fp_t x, fp_t y, fp_t z)
void ecfp_add_affine_std (ecfp_pt res, const ecfp_pt a, const ecfp_pt b)
Adds two points of an elliptic curve group over a prime field using affine coordinates via projective coordinates.
void ecfp_add_affine_direct_std (ecfp_pt res, const ecfp_pt a, const ecfp_pt b)
Adds two points of an elliptic curve group over a prime field using affine coordinates.
void ecfp_add_proj_std (ecfp_proj_pt res, const ecfp_proj_pt a, const ecfp_pt b)
Adds two points of an elliptic curve group over a prime field using mixed affine and projective coordinates.
void ecfp_dbl_affine_std (ecfp_pt res, const ecfp_pt a)
Calculates the double of a point of an elliptic curve group over a prime field using affine coordinates via projective coordinates.
void ecfp_dbl_affine_direct_std (ecfp_pt res, const ecfp_pt a)
Calculates the double of a point of an elliptic curve group over a prime field using affine coordinates.
void ecfp_dbl_proj_std (ecfp_proj_pt res, ecfp_proj_pt a)
Calculates the double of a point of an elliptic curve group over a prime field using projective coordinates.
void ecfp_mul_l2rb_std (ecfp_pt res, const ecfp_pt a, const fp_t k)
Performs a left-to-right binary elliptic curve point multiplication.
void ecfp_mul_montyladder_std (ecfp_pt res, const ecfp_pt a, const fp_t k)
Elliptic curve point multiplication using a Montgomery ladder with co-Z coordinates.
void ecfp_get_projective_std (ecfp_proj_pt projective, const ecfp_pt affine)
Converts an elliptic curve point in affine coordinates to an elliptic curve point in projective coordinates.
void ecfp_get_jacobian_projective_rnd_std (ecfp_proj_pt projective, const ecfp_pt affine)
Converts an elliptic curve point in affine coordinates to an elliptic curve point in randomized jacobian projective coordinates.
void ecfp_get_affine_from_jacobian_std (ecfp_pt affine, const ecfp_proj_pt projective)
Converts an elliptic curve point in jacobian projective coordinates to an elliptic curve point in affine coordinates.
void ecfp_neg_affine_std (ecfp_pt a)
Negates an elliptic curve point in affine coordinates, i.e.
void ecfp_neg_proj_std (ecfp_proj_pt a)
Negates an elliptic curve point in projective coordinates, i.e.
void ecfp_copy_std (ecfp_pt res, const ecfp_pt a)
Copies a point of an elliptic curve group over a prime field.
void ecfp_clear_std (ecfp_pt a)
Clears a point of an elliptic curve group over a prime field.
void ecfp_hash_to_point_std (ecfp_pt res, const bigint_t t)
Hashes an integer to a point in an elliptic curve group over a prime field.
void ecfp_to_montgomery_std (ecfp_pt res, const ecfp_pt a)
Converts an elliptic curve point to the Montgomery domain.
void ecfp_from_montgomery_std (ecfp_pt res, const ecfp_pt a)
Converts an elliptic curve point in Montgomery domain back.
void ecfp_rand_std (ecfp_pt res)
Generates a random elliptic curve point.
Function Documentation
void ecfp_add_affine_direct_std (ecfp_pt res, const ecfp_pt a, const ecfp_pt b)
Adds two points of an elliptic curve group over a prime field using affine coordinates.
Parameters
res the sum of the two points
a operand a
b operand b
Definition at line 66 of file ecfp.c.
References bi_compare, ecfp_dbl_affine, fp_copy, fp_inv, fp_mul, fp_sqr, fp_sub, ecpoint_fp::infinity, ecpoint_fp::x, and ecpoint_fp::y.
void ecfp_add_affine_std (ecfp_pt res, const ecfp_pt a, const ecfp_pt b)
Adds two points of an elliptic curve group over a prime field using affine coordinates via projective coordinates.
Parameters
res the sum of the two points
a operand a
b operand b
Definition at line 52 of file ecfp.c.
References ecfp_add_proj, ecfp_get_affine_from_jacobian, and ecfp_get_jacobian_projective.
void ecfp_add_dbl_coz_std (fp_t x1, fp_t x2, fp_t z, const fp_t x_d)
Performs a mixed add and double operation in co-Z coordinates to be used in a specialize Montgomery ladder implementation of the elliptic curve point multiplication.
Note that the function updates the parameters!
Parameters
x1 the x-coordinate of the first point in the Montgomery ladder
x2 the x-coordinate of the second point in the Montgomery ladder
z the common z-coordinate of the two points in the Montgomery ladder
x_d the constant difference of the x-coordinates of the two points in the Montgomery ladder
Algorithm 5 from "Memory-Constrained Implementations of Elliptic Curve Cryptography in Co-Z Coordinate Representation", Hutter et. al.
Definition at line 490 of file ecfp.c.
References EC_PARAM_4B, EC_PARAM_A, EC_PARAM_B, fp_add, fp_dbl, fp_mul, fp_sqr, and fp_sub.
Referenced by ecfp_mul_montyladder_std().
void ecfp_add_proj_std (ecfp_proj_pt res, const ecfp_proj_pt a, const ecfp_pt b)
Adds two points of an elliptic curve group over a prime field using mixed affine and projective coordinates.
Parameters
res the projective result
a the projective point operand
b the affine point operand
Definition at line 188 of file ecfp.c.
References bi_compare, bi_zero, ecfp_dbl_proj, fp_add, fp_copy, fp_mul, FP_ONE, fp_sqr, fp_sub, ecpoint_fp::infinity, ecpoint_fp_proj::infinity, ecpoint_fp::x, ecpoint_fp_proj::x, ecpoint_fp::y, ecpoint_fp_proj::y, and ecpoint_fp_proj::z.
void ecfp_clear_std (ecfp_pt a)
Clears a point of an elliptic curve group over a prime field.
Parameters
a the elliptic curve point in affine coordinates
Definition at line 765 of file ecfp.c.
References fp_clear, ecpoint_fp::infinity, ecpoint_fp::x, and ecpoint_fp::y.
void ecfp_copy_std (ecfp_pt res, const ecfp_pt a)
Copies a point of an elliptic curve group over a prime field.
Parameters
res the resulting copy
a the affine input point to be copied
Definition at line 755 of file ecfp.c.
References fp_copy, ecpoint_fp::infinity, ecpoint_fp::x, and ecpoint_fp::y.
void ecfp_dbl_affine_direct_std (ecfp_pt res, const ecfp_pt a)
Calculates the double of a point of an elliptic curve group over a prime field using affine coordinates.
Parameters
res the result
a the point operand
Definition at line 270 of file ecfp.c.
References EC_PARAM_A, fp_add, fp_copy, fp_dbl, fp_inv, fp_mul, fp_sqr, fp_sub, ecpoint_fp::infinity, ecpoint_fp::x, and ecpoint_fp::y.
void ecfp_dbl_affine_std (ecfp_pt res, const ecfp_pt a)
Calculates the double of a point of an elliptic curve group over a prime field using affine coordinates via projective coordinates.
Parameters
res the result
a the point operand
Definition at line 256 of file ecfp.c.
References ecfp_dbl_proj, ecfp_get_affine_from_jacobian, and ecfp_get_jacobian_projective.
void ecfp_dbl_proj_std (ecfp_proj_pt res, ecfp_proj_pt a)
Calculates the double of a point of an elliptic curve group over a prime field using projective coordinates.
Parameters
res the projective result
a the projective point operand
Definition at line 362 of file ecfp.c.
References EC_PARAM_A, fp_add, fp_copy, fp_dbl, fp_hlv, fp_mul, fp_sqr, fp_sub, ecpoint_fp_proj::infinity, ecpoint_fp_proj::x, ecpoint_fp_proj::y, and ecpoint_fp_proj::z.
void ecfp_from_montgomery_std (ecfp_pt res, const ecfp_pt a)
Converts an elliptic curve point in Montgomery domain back.
Parameters
res the resulting point in normal number format
a the elliptc curve point in Montgomery domain to be converted
Definition at line 913 of file ecfp.c.
References fp_from_montgomery, ecpoint_fp::infinity, ecpoint_fp::x, and ecpoint_fp::y.
void ecfp_get_affine_from_jacobian_std (ecfp_pt affine, const ecfp_proj_pt projective)
Converts an elliptic curve point in jacobian projective coordinates to an elliptic curve point in affine coordinates.
Parameters
affine the resulting affine elliptic curve point
projective the input projective elliptic curve point
Definition at line 720 of file ecfp.c.
References fp_inv, fp_mul, fp_sqr, ecpoint_fp::infinity, ecpoint_fp_proj::infinity, ecpoint_fp::x, ecpoint_fp_proj::x, ecpoint_fp::y, ecpoint_fp_proj::y, and ecpoint_fp_proj::z.
void ecfp_get_jacobian_projective_rnd_std (ecfp_proj_pt projective, const ecfp_pt affine)
Converts an elliptic curve point in affine coordinates to an elliptic curve point in randomized jacobian projective coordinates.
Parameters
projective the resulting randomized projective elliptic curve point
affine the input affine elliptic curve point
Definition at line 692 of file ecfp.c.
References cprng_get_bytes(), FP_BYTES, fp_mul, fp_rdc, fp_sqr, ecpoint_fp::infinity, ecpoint_fp_proj::infinity, ecpoint_fp::x, ecpoint_fp_proj::x, ecpoint_fp::y, ecpoint_fp_proj::y, and ecpoint_fp_proj::z.
void ecfp_get_projective_std (ecfp_proj_pt projective, const ecfp_pt affine)
Converts an elliptic curve point in affine coordinates to an elliptic curve point in projective coordinates.
Parameters
projective the resulting projective elliptic curve point
affine the input affine elliptic curve point
Definition at line 675 of file ecfp.c.
References fp_copy, FP_ONE, ecpoint_fp::infinity, ecpoint_fp_proj::infinity, ecpoint_fp::x, ecpoint_fp_proj::x, ecpoint_fp::y, ecpoint_fp_proj::y, and ecpoint_fp_proj::z.
void ecfp_hash_to_point_std (ecfp_pt res, const bigint_t t)
Hashes an integer to a point in an elliptic curve group over a prime field.
Parameters
res the resulting elliptic curve point
t the integer to be hashed
Definition at line 839 of file ecfp.c.
References EC_PARAM_B, fp_add, fp_copy, fp_dbl, fp_hlv, fp_inv, fp_legendre, fp_mul, fp_neg, FP_ONE, fp_sqr, fp_sqrt, fp_sub, ecpoint_fp::infinity, ecpoint_fp::x, and ecpoint_fp::y.
void ecfp_mul_l2rb_std (ecfp_pt res, const ecfp_pt a, const fp_t k)
Performs a left-to-right binary elliptic curve point multiplication.
Parameters
res the resulting product
a the point operand
k the scalar operand
Definition at line 417 of file ecfp.c.
References bi_get_msb, bi_test_bit, ecfp_add_proj, ecfp_dbl_proj, ecfp_get_affine_from_jacobian, and ecpoint_fp_proj::infinity.
void ecfp_mul_montyladder_std (ecfp_pt res, const ecfp_pt a, const fp_t k)
Elliptic curve point multiplication using a Montgomery ladder with co-Z coordinates.
Parameters
res the resulting product
a the point operand
k the scalar operand
Definition at line 621 of file ecfp.c.
References bi_get_msb, bi_test_bit, bi_zero, cprng_get_bytes(), ecfp_add_dbl_coz_std(), ecfp_recover_full_coord_coz_std(), ecfp_verify_coordinates(), ecfp_verify_homogeneous_projective_coordinates(), FP_BYTES, fp_copy, fp_inv, fp_mul, fp_rdc, ecpoint_fp::infinity, ecpoint_fp::x, and ecpoint_fp::y.
void ecfp_neg_affine_std (ecfp_pt a)
Negates an elliptic curve point in affine coordinates, i.e.
computes -P.
Parameters
a the elliptic curve point (input and result)
Definition at line 738 of file ecfp.c.
References fp_neg, and ecpoint_fp::y.
void ecfp_neg_proj_std (ecfp_proj_pt a)
Negates an elliptic curve point in projective coordinates, i.e.
computes -P.
Parameters
a the elliptic curve point (input and result)
Definition at line 746 of file ecfp.c.
References fp_neg, and ecpoint_fp_proj::y.
void ecfp_rand_std (ecfp_pt res)
Generates a random elliptic curve point.
To this end, we generate a random scalar (that is not known by anyone) and multiply it with the base point.
Parameters
res [out] the random point.
Definition at line 925 of file ecfp.c.
References BI_BYTES, bi_compare, bi_zero, cprng_get_bytes(), ECFP_GENERATOR, ecfp_mul, and fp_rdc_n.
void ecfp_recover_full_coord_coz_std (fp_t x1, fp_t x2, fp_t z, const fp_t x_d, const fp_t y_d)
Recovers the coordinates of the result of the Montgomery ladder elliptic curve point multiplication using co-Z coordinates.
Parameters
x1 the first point in the Montgomery ladder implementation (out: the x-coordinate of the resulting point)
x2 the second point in the Montgomery ladder implementation (out: the y-coordinate of the resulting point)
z the common z-coordinate of the two points in the Montgomery ladder
x_d the constant difference of the x-coordinates of the two points in the Montgomery ladder
y_d the difference of the y-coordinates of the two input points
Algorithm 7 from "Memory-Constrained Implementations of Elliptic Curve Cryptography in Co-Z Coordinate Representation", Hutter et. al.
Definition at line 573 of file ecfp.c.
References EC_PARAM_4B, EC_PARAM_A, EC_PARAM_B, fp_add, fp_dbl, fp_mul, fp_sqr, and fp_sub.
Referenced by ecfp_mul_montyladder_std().
void ecfp_to_montgomery_std (ecfp_pt res, const ecfp_pt a)
Converts an elliptic curve point to the Montgomery domain.
Parameters
res the resulting point in Montgomery domain
a the elliptic curve point to be converted
Definition at line 902 of file ecfp.c.
References fp_to_montgomery, ecpoint_fp::infinity, ecpoint_fp::x, and ecpoint_fp::y.
int ecfp_verify_coordinates (fp_t x, fp_t y)
Definition at line 437 of file ecfp.c.
References bi_compare, EC_PARAM_A, EC_PARAM_B, fp_add, fp_mul, and fp_sqr.
Referenced by ecfp_mul_montyladder_std().
int ecfp_verify_homogeneous_projective_coordinates (fp_t x, fp_t y, fp_t z)
Definition at line 455 of file ecfp.c.
References bi_compare, EC_PARAM_A, EC_PARAM_B, fp_add, fp_mul, and fp_sqr.
Referenced by ecfp_mul_montyladder_std().