Pairings: /home/work/workspace/bipair_in_c/src/base/std/ec/ecfp2.c File Reference
ecfp2.c File Reference
#include "ec/ec.h"
#include "fp/fp2.h"
#include "fp/fp.h"
#include "bigint/bi.h"
#include "rand.h"
Functions
void ecfp2_add_affine_std (ecfp2_pt res, const ecfp2_pt a, const ecfp2_pt b)
Adds two points of an elliptic curve group over the quadratic extension of a prime field using affine coordinates via projective coordinates.
void ecfp2_add_affine_direct_std (ecfp2_pt res, const ecfp2_pt a, const ecfp2_pt b)
Adds two points of an elliptic curve group over the quadratic extension of a prime field using affine coordinates.
void ecfp2_add_proj_std (ecfp2_proj_pt res, const ecfp2_proj_pt a, const ecfp2_pt b)
Adds two points of an elliptic curve group over the quadratic extension of a prime field using mixed affine and projective coordinates.
void ecfp2_dbl_affine_std (ecfp2_pt res, const ecfp2_pt a)
Calculates the double of a point of an elliptic curve group over the quadratic extension of a prime field using affine coordinates via projective coordinates.
void ecfp2_dbl_affine_direct_std (ecfp2_pt res, const ecfp2_pt a)
Calculates the double of a point of an elliptic curve group over the quadratic extension of a prime field using affine coordinates.
void ecfp2_dbl_proj_std (ecfp2_proj_pt res, const ecfp2_proj_pt a)
Calculates the double of a point of an elliptic curve group over the quadratic extension of a prime field using mixed affine and projective coordinates.
void ecfp2_neg_affine_std (ecfp2_pt a)
Negates a point of an elliptic curve group defined over the quadratic extension of a prime field, i.e., computes -P.
void ecfp2_neg_proj_std (ecfp2_proj_pt a)
Negates a point of an elliptic curve group defined over the quadratic extension of a prime field, i.e., computes -P.
void ecfp2_mul_l2rb_std (ecfp2_pt res, const ecfp2_pt a, const fp_t k)
Performs the multiplication of a point of an elliptic curve group defined over the quadratic extension of a prime field with a scalar.
void ecfp2_add_dbl_coz_std (fp2_t x1, fp2_t x2, fp2_t z, const fp2_t x_d)
Performs a mixed add and double operation in co-Z coordinates to be used in a specialize Montgomery ladder implementation of the elliptic curve point multiplication.
void ecfp2_recover_full_coord_coz_std (fp2_t x1, fp2_t x2, fp2_t z, const fp2_t x_d, const fp2_t y_d)
Recovers the coordinates of the result of the Montgomery ladder elliptic curve point multiplication using co-Z coordinates.
int ecfp2_verify_coordinates (fp2_t x, fp2_t y)
int ecfp2_verify_homogeneous_projective_coordinates (fp2_t x, fp2_t y, fp2_t z)
void ecfp2_mul_montyladder_std (ecfp2_pt res, const ecfp2_pt a, const fp_t k)
Elliptic curve point multiplication using a Montgomery ladder with co-Z coordinates.
void ecfp2_get_affine_from_jacobian_std (ecfp2_pt affine, const ecfp2_proj_pt projective)
Converts an elliptic curve point in jacobian projective coordinates to an elliptic curve point in affine coordinates.
void ecfp2_get_projective_std (ecfp2_proj_pt projective, const ecfp2_pt affine)
Converts an elliptic curve point in affine coordinates to an elliptic curve point in projective coordinates.
void ecfp2_get_jacobian_projective_rnd_std (ecfp2_proj_pt projective, const ecfp2_pt affine)
Converts an elliptic curve point in affine coordinates to a randomized elliptic curve point in jacobian projective coordinates.
void ecfp2_get_homogeneous_projective_rnd_std (ecfp2_proj_pt projective, const ecfp2_pt affine)
Converts an elliptic curve point in affine coordinates to a randomized elliptic curve point in homogeneous projective coordinates.
void ecfp2_copy_std (ecfp2_pt res, const ecfp2_pt a)
Copies a point of an elliptic curve group over the quadratic extension of a prime field.
void ecfp2_clear_std (ecfp2_pt a)
Clears a point of an elliptic curve group over the quadratic extension of a prime field.
void ecfp2_frobenius_map_precomp_std (ecfp2_pt res, const ecfp2_pt a, const word_t i)
Computes the frobenius map of a point of an elliptic curve group over the quadratic extension of a prime field.
void ecfp2_frobenius_map_std (ecfp2_pt res, const ecfp2_pt a, const word_t i)
Computes the frobenius map of a point of an elliptic curve group over the quadratic extension of a prime field.
int ecfp2_compare_std (ecfp2_proj_pt a, const ecfp2_proj_pt b)
Compares two points of an elliptic curve group defined over the quadratic extension of a prime field.
void ecfp2_hash_to_point_std (ecfp2_pt res, const bigint_t t)
Hashes an integer to a point in the elliptic curve group over the quadratic extension of a prime field.
void ecfp2_to_montgomery_std (ecfp2_pt res, const ecfp2_pt a)
Converts an elliptic curve point to the Montgomery domain.
void ecfp2_from_montgomery_std (ecfp2_pt res, const ecfp2_pt a)
Converts an elliptic curve point in Montgomery domain back.
void ecfp2_rand_std (ecfp2_pt res)
Generate random point.
Function Documentation
void ecfp2_add_affine_direct_std (ecfp2_pt res, const ecfp2_pt a, const ecfp2_pt b)
Adds two points of an elliptic curve group over the quadratic extension of a prime field using affine coordinates.
Parameters
res the sum of the two points
a operand a
b operand b
Definition at line 64 of file ecfp2.c.
References bi_compare, ecfp2_dbl_affine, fp2_copy, fp2_inv, fp2_mul, fp2_sqr, fp2_sub, ecpoint_fp2::infinity, ecpoint_fp2::x, and ecpoint_fp2::y.
void ecfp2_add_affine_std (ecfp2_pt res, const ecfp2_pt a, const ecfp2_pt b)
Adds two points of an elliptic curve group over the quadratic extension of a prime field using affine coordinates via projective coordinates.
Parameters
res the sum of the two points
a operand a
b operand b
Definition at line 49 of file ecfp2.c.
References ecfp2_add_proj, ecfp2_get_affine_from_jacobian, and ecfp2_get_jacobian_projective.
void ecfp2_add_dbl_coz_std (fp2_t x1, fp2_t x2, fp2_t z, const fp2_t x_d)
Performs a mixed add and double operation in co-Z coordinates to be used in a specialize Montgomery ladder implementation of the elliptic curve point multiplication.
Note that the function updates the parameters!
Parameters
x1 the x-coordinate of the first point in the Montgomery ladder
x2 the x-coordinate of the second point in the Montgomery ladder
z the common z-coordinate of the two points in the Montgomery ladder
x_d the constant difference of the x-coordinates of the two points in the Montgomery ladder
Algorithm 5 from "Memory-Constrained Implementations of Elliptic Curve Cryptography in Co-Z Coordinate Representation", Hutter et. al.
Definition at line 353 of file ecfp2.c.
References EC_PARAM_4B, EC_PARAM_A, EC_PARAM_B, fp2_add, fp2_dbl, fp2_div_qnr, fp2_mul, fp2_sqr, fp2_sub, fp_clear, and fp_copy.
Referenced by ecfp2_mul_montyladder_std().
void ecfp2_add_proj_std (ecfp2_proj_pt res, const ecfp2_proj_pt a, const ecfp2_pt b)
Adds two points of an elliptic curve group over the quadratic extension of a prime field using mixed affine and projective coordinates.
Parameters
res the projective sum of the two points
a the projective point operand
b the affine point operand
Definition at line 118 of file ecfp2.c.
References bi_compare, bi_zero, ecfp2_dbl_proj, fp2_add, fp2_copy, fp2_mul, fp2_sqr, fp2_sub, fp_copy, FP_ONE, ecpoint_fp2::infinity, ecpoint_fp2_proj::infinity, ecpoint_fp2::x, ecpoint_fp2_proj::x, ecpoint_fp2::y, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.
void ecfp2_clear_std (ecfp2_pt a)
Clears a point of an elliptic curve group over the quadratic extension of a prime field.
Parameters
a the elliptic curve point in affine coordinates
Definition at line 719 of file ecfp2.c.
References fp2_clear, ecpoint_fp2::infinity, ecpoint_fp2::x, and ecpoint_fp2::y.
int ecfp2_compare_std (ecfp2_proj_pt a, const ecfp2_proj_pt b)
Compares two points of an elliptic curve group defined over the quadratic extension of a prime field.
Note that the check for equality does merely check the absolute values of the coordinates, i.e., it does not recognize equal projective points in different representations.
Parameters
a the first projective elliptic curve point
b the second projective elliptic curve point
Returns
0 if equal, 1 otherwise
Definition at line 799 of file ecfp2.c.
References bi_compare, ecpoint_fp2_proj::infinity, ecpoint_fp2_proj::x, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.
void ecfp2_copy_std (ecfp2_pt res, const ecfp2_pt a)
Copies a point of an elliptic curve group over the quadratic extension of a prime field.
Parameters
res the resulting copy
a the affine input point to be copied
Definition at line 708 of file ecfp2.c.
References fp2_copy, ecpoint_fp2::infinity, ecpoint_fp2::x, and ecpoint_fp2::y.
void ecfp2_dbl_affine_direct_std (ecfp2_pt res, const ecfp2_pt a)
Calculates the double of a point of an elliptic curve group over the quadratic extension of a prime field using affine coordinates.
Uses the elliptic curve twist of the originally defined curve.
Parameters
res the result
a the point operand
Definition at line 205 of file ecfp2.c.
References EC_PARAM_A, fp2_add, fp2_copy, fp2_dbl, fp2_div_qnr, fp2_inv, fp2_mul, fp2_sqr, fp2_sub, fp_clear, fp_copy, ecpoint_fp2::infinity, ecpoint_fp2::x, and ecpoint_fp2::y.
void ecfp2_dbl_affine_std (ecfp2_pt res, const ecfp2_pt a)
Calculates the double of a point of an elliptic curve group over the quadratic extension of a prime field using affine coordinates via projective coordinates.
Uses the elliptic curve twist of the originally defined curve.
Parameters
res the result
a the point operand
Definition at line 190 of file ecfp2.c.
References ecfp2_dbl_proj, ecfp2_get_affine_from_jacobian, and ecfp2_get_jacobian_projective.
void ecfp2_dbl_proj_std (ecfp2_proj_pt res, const ecfp2_proj_pt a)
Calculates the double of a point of an elliptic curve group over the quadratic extension of a prime field using mixed affine and projective coordinates.
Uses the elliptic curve twist of the originally defined curve.
Parameters
res the result
a the point operand
Definition at line 247 of file ecfp2.c.
References EC_PARAM_A, fp2_add, fp2_copy, fp2_dbl, fp2_div_qnr, fp2_hlv, fp2_mul, fp2_sqr, fp2_sub, fp_clear, fp_copy, ecpoint_fp2_proj::infinity, ecpoint_fp2_proj::x, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.
void ecfp2_frobenius_map_precomp_std (ecfp2_pt res, const ecfp2_pt a, const word_t i)
Computes the frobenius map of a point of an elliptic curve group over the quadratic extension of a prime field.
Uses a precomputed table for the roots of the quadratic non-residue in Fp2.
Parameters
res the resulting elliptic curve point
a the operand point
i the order of frobenius
Definition at line 733 of file ecfp2.c.
References ecfp2_copy, fp2_frobenius_map, fp2_mul, ROOT_RESIDUE_FP4, ecpoint_fp2::x, and ecpoint_fp2::y.
void ecfp2_frobenius_map_std (ecfp2_pt res, const ecfp2_pt a, const word_t i)
Computes the frobenius map of a point of an elliptic curve group over the quadratic extension of a prime field.
The function computes everything from scratch.
Parameters
res the resulting elliptic curve point
a the operand point
i the order of frobenius
Definition at line 759 of file ecfp2.c.
References bi_copy, bi_div3, bi_one, bi_shift_right_one, bi_subtract, ecfp2_copy, fp2_exp, fp2_frobenius_map, fp2_mul, fp2_mul_qnr, fp2_sqr, fp_clear, fp_copy, FP_ONE, PRIME_P, ecpoint_fp2::x, and ecpoint_fp2::y.
void ecfp2_from_montgomery_std (ecfp2_pt res, const ecfp2_pt a)
Converts an elliptic curve point in Montgomery domain back.
Parameters
res the resulting point in normal number format
a the elliptc curve point in Montgomery domain to be converted
Definition at line 917 of file ecfp2.c.
References fp2_from_montgomery, ecpoint_fp2::infinity, ecpoint_fp2::x, and ecpoint_fp2::y.
void ecfp2_get_affine_from_jacobian_std (ecfp2_pt affine, const ecfp2_proj_pt projective)
Converts an elliptic curve point in jacobian projective coordinates to an elliptic curve point in affine coordinates.
Parameters
affine the resulting affine elliptic curve point
projective the input projective elliptic curve point
Definition at line 617 of file ecfp2.c.
References fp2_inv, fp2_mul, fp2_sqr, ecpoint_fp2::infinity, ecpoint_fp2_proj::infinity, ecpoint_fp2::x, ecpoint_fp2_proj::x, ecpoint_fp2::y, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.
void ecfp2_get_homogeneous_projective_rnd_std (ecfp2_proj_pt projective, const ecfp2_pt affine)
Converts an elliptic curve point in affine coordinates to a randomized elliptic curve point in homogeneous projective coordinates.
Parameters
projective the resulting randomized, projective elliptic curve point
affine the input affine elliptic curve point
Definition at line 683 of file ecfp2.c.
References cprng_get_bytes(), fp2_mul, FP_BYTES, fp_rdc, ecpoint_fp2::infinity, ecpoint_fp2_proj::infinity, ecpoint_fp2::x, ecpoint_fp2_proj::x, ecpoint_fp2::y, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.
void ecfp2_get_jacobian_projective_rnd_std (ecfp2_proj_pt projective, const ecfp2_pt affine)
Converts an elliptic curve point in affine coordinates to a randomized elliptic curve point in jacobian projective coordinates.
Parameters
projective the resulting randomized, projective elliptic curve point
affine the input affine elliptic curve point
Definition at line 654 of file ecfp2.c.
References cprng_get_bytes(), fp2_mul, fp2_sqr, FP_BYTES, fp_rdc, ecpoint_fp2::infinity, ecpoint_fp2_proj::infinity, ecpoint_fp2::x, ecpoint_fp2_proj::x, ecpoint_fp2::y, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.
void ecfp2_get_projective_std (ecfp2_proj_pt projective, const ecfp2_pt affine)
Converts an elliptic curve point in affine coordinates to an elliptic curve point in projective coordinates.
Parameters
projective the resulting projective elliptic curve point
affine the input affine elliptic curve point
Definition at line 637 of file ecfp2.c.
References fp2_copy, fp_clear, fp_copy, FP_ONE, ecpoint_fp2::infinity, ecpoint_fp2_proj::infinity, ecpoint_fp2::x, ecpoint_fp2_proj::x, ecpoint_fp2::y, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.
void ecfp2_hash_to_point_std (ecfp2_pt res, const bigint_t t)
Hashes an integer to a point in the elliptic curve group over the quadratic extension of a prime field.
Parameters
res the resulting elliptic curve point
t the integer to be hashed
Definition at line 812 of file ecfp2.c.
References EC_PARAM_B, EC_PARAM_X, ecfp2_add_affine, ecfp2_add_proj, ecfp2_dbl_affine, ecfp2_frobenius_map, ecfp2_get_affine_from_jacobian, ecfp2_get_jacobian_projective, ecfp2_mul, ecfp2_neg_affine, fp2_add, fp2_copy, fp2_div_qnr, fp2_hlv, fp2_inv, fp2_legendre, fp2_mul, fp2_mulfp, fp2_neg, fp2_sqr, fp2_sqrt, fp2_sub, fp_add, fp_clear, fp_copy, fp_dbl, fp_legendre, fp_neg, FP_ONE, fp_sqr, fp_sqrt, fp_sub, ecpoint_fp2::infinity, ecpoint_fp2::x, and ecpoint_fp2::y.
void ecfp2_mul_l2rb_std (ecfp2_pt res, const ecfp2_pt a, const fp_t k)
Performs the multiplication of a point of an elliptic curve group defined over the quadratic extension of a prime field with a scalar.
Parameters
res the resulting product
a the elliptic curve point to be multiplied
k the scalar operand
Definition at line 324 of file ecfp2.c.
References bi_get_msb, bi_test_bit, ecfp2_add_proj, ecfp2_dbl_proj, ecfp2_get_affine_from_jacobian, and ecpoint_fp2_proj::infinity.
void ecfp2_mul_montyladder_std (ecfp2_pt res, const ecfp2_pt a, const fp_t k)
Elliptic curve point multiplication using a Montgomery ladder with co-Z coordinates.
Parameters
res the resulting product
a the point operand
k the scalar operand
Definition at line 561 of file ecfp2.c.
References bi_get_msb, bi_test_bit, cprng_get_bytes(), ecfp2_add_dbl_coz_std(), ecfp2_recover_full_coord_coz_std(), ecfp2_verify_coordinates(), ecfp2_verify_homogeneous_projective_coordinates(), fp2_clear, fp2_inv, fp2_mul, FP_BYTES, fp_rdc, ecpoint_fp2::infinity, ecpoint_fp2::x, and ecpoint_fp2::y.
void ecfp2_neg_affine_std (ecfp2_pt a)
Negates a point of an elliptic curve group defined over the quadratic extension of a prime field, i.e., computes -P.
Parameters
a the affine elliptic curve point (out: the negated point)
Definition at line 304 of file ecfp2.c.
References fp2_neg, and ecpoint_fp2::y.
void ecfp2_neg_proj_std (ecfp2_proj_pt a)
Negates a point of an elliptic curve group defined over the quadratic extension of a prime field, i.e., computes -P.
Parameters
a the projective elliptic curve point (out: the negated point)
Definition at line 313 of file ecfp2.c.
References fp2_neg, and ecpoint_fp2_proj::y.
void ecfp2_rand_std (ecfp2_pt res)
Generate random point.
To this end, we generate a random scalar (that is not known by anyone) and multiply it with the base point.
Parameters
res the randomly generated point.
Definition at line 929 of file ecfp2.c.
References BI_BYTES, bi_compare, bi_zero, cprng_get_bytes(), ECFP2_GENERATOR, ecfp2_mul, and fp_rdc_n.
void ecfp2_recover_full_coord_coz_std (fp2_t x1, fp2_t x2, fp2_t z, const fp2_t x_d, const fp2_t y_d)
Recovers the coordinates of the result of the Montgomery ladder elliptic curve point multiplication using co-Z coordinates.
Parameters
x1 the first point in the Montgomery ladder implementation (out: the x-coordinate of the resulting point)
x2 the second point in the Montgomery ladder implementation (out: the y-coordinate of the resulting point)
z the common z-coordinate of the two points in the Montgomery ladder
x_d the constant difference of the x-coordinates of the two points in the Montgomery ladder
y_d the difference of the y-coordinates of the two input points
Algorithm 7 from "Memory-Constrained Implementations of Elliptic Curve Cryptography in Co-Z Coordinate Representation", Hutter et. al.
Definition at line 445 of file ecfp2.c.
References EC_PARAM_4B, EC_PARAM_A, EC_PARAM_B, fp2_add, fp2_dbl, fp2_div_qnr, fp2_mul, fp2_sqr, fp2_sub, fp_clear, and fp_copy.
Referenced by ecfp2_mul_montyladder_std().
void ecfp2_to_montgomery_std (ecfp2_pt res, const ecfp2_pt a)
Converts an elliptic curve point to the Montgomery domain.
Parameters
res the resulting point in Montgomery domain
a the elliptic curve point to be converted
Definition at line 906 of file ecfp2.c.
References fp2_to_montgomery, ecpoint_fp2::infinity, ecpoint_fp2::x, and ecpoint_fp2::y.
int ecfp2_verify_coordinates (fp2_t x, fp2_t y)
Definition at line 498 of file ecfp2.c.
References bi_compare, EC_PARAM_A, EC_PARAM_B, fp2_add, fp2_div_qnr, fp2_mul, fp2_sqr, fp_clear, and fp_copy.
Referenced by ecfp2_mul_montyladder_std().
int ecfp2_verify_homogeneous_projective_coordinates (fp2_t x, fp2_t y, fp2_t z)
Definition at line 523 of file ecfp2.c.
References bi_compare, EC_PARAM_A, EC_PARAM_B, fp2_add, fp2_div_qnr, fp2_mul, fp2_sqr, fp_clear, and fp_copy.
Referenced by ecfp2_mul_montyladder_std().