Pairings: /home/work/workspace/bipair_in_c/include/fp/fp12_std.h File Reference
fp12_std.h File Reference
#include "types.h"
Functions
void fp12_add_std (fp12_t res, const fp12_t a, const fp12_t b)
Adds two elements in Fp12.
void fp12_sub_std (fp12_t res, const fp12_t a, const fp12_t b)
Subtracts two elements in Fp12.
void fp12_neg_std (fp12_t res, const fp12_t a)
Negates one element in Fp12.
void fp12_mul_std (fp12_t res, const fp12_t a, const fp12_t b)
Simple multiplication in Fp12 using an extended Karatsuba method.
void fp12_mul_tk3_std (fp12_t res, const fp12_t a, const fp12_t b)
Multiplication based on the Toom-Cook Method, but with the result being factored by 6.
void fp12_sqr_std (fp12_t res, const fp12_t a)
Squares one element in Fp12.
void fp12_sqr_cyclotomic_std (fp12_t res, const fp12_t a)
Squares one element of cyclotomic subgroup in Fp12.
void fp12_sqr_cyclotomic_compressed (fp12_t res, const fp12_t a)
Compressed squaring as presented by Karabina in "Squaring in Cyclotomic Subgroups".
void fp12_mul_sparse_std (fp12_t res, const fp12_t a, const fp4_t b0, const fp2_t b10)
Performs a multiplication of one element in Fp12 with a sparse element in Fp12.
void fp12_inv_std (fp12_t res, const fp12_t a)
Inversion of an element in Fp12 using direct inversion formulas.
void fp12_exp_montyladder_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation of elements in Fp12.
void fp12_exp_masked_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation of elements in Fp12.
void fp12_exp_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation of elements in Fp12, which is not secured against any attack, but uses dummy operations.
void fp12_exp_cyclotomic_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation in the cyclotomic subgroup of Fp12, which is not secured against any attack, but uses dummy operations.
void fp12_exp_cyclotomic_montyladder_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation in the cyclotomic subgroup of Fp12.
void fp12_exp_cyclotomic_masked_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation in the cyclotomic subgroup of Fp12.
void fp12_final_exp_std (fp12_t res, const fp12_t a, const bigint_t b)
Performs an exponentiation involved in the final exponentiation of the pairing.
void fp12_final_mulexp_std (fp12_t res, fp12_t a, const bigint_t b)
Exponentiates a by b and directly multiplies the result with the result.
void fp12_final_exp_bn254 (fp12_t res, const fp12_t a, const bigint_t b)
Performs an exponentiation involved in the final exponentiation of the pairing.
void fp12_hlv_std (fp12_t res, const fp12_t a)
Halves one element in Fp12.
void fp12_frobenius_map_std (fp12_t res, const fp12_t a, const word_t i)
Computes the frobenius map of an element in Fp12.
void fp12_frobenius_map_precomp_std (fp12_t res, const fp12_t a, const word_t i)
Computes the frobenius map of an element in Fp12.
void fp12_conjugate_std (fp12_t res, const fp12_t a, const word_t i)
Computes the conjugate of an element in Fp12, which are special cases of the frobenius operation.
void fp12_decompress_std (fp12_t a)
Decompression from Karabina in "Squaring in cyclotomic subgroups".
void fp12_to_montgomery_std (fp12_t res, const fp12_t a)
Converts an element in Fp12 to the Montgomery domain.
void fp12_from_montgomery_std (fp12_t res, const fp12_t a)
Converts an element in Fp12 (Montgomery domain) back to normal.
void fp12_rdc_std (fp12_t a)
Reduces an element in Fp12 with the fixed modulus.
void fp12_clear_std (fp12_t a)
Clears one Fp12 element.
void fp12_copy_std (fp12_t res, const fp12_t a)
Copies one Fp12 element.
Function Documentation
void fp12_add_std (fp12_t res, const fp12_t a, const fp12_t b)
Adds two elements in Fp12.
Parameters
res the destination of the sum
a first operand
b second operand
Definition at line 48 of file fp12.c.
References fp4_add.
void fp12_clear_std (fp12_t a)
Clears one Fp12 element.
Parameters
a the element to be set to zero
Definition at line 925 of file fp12.c.
References fp4_clear.
void fp12_conjugate_std (fp12_t res, const fp12_t a, const word_t i)
Computes the conjugate of an element in Fp12, which are special cases of the frobenius operation.
The function uses precomputed roots of the quadratic non-residue in Fp2.
Parameters
res the conjugate
a the input element
i the order of the conjugate
Definition at line 906 of file fp12.c.
References fp2_copy, and fp2_neg.
void fp12_copy_std (fp12_t res, const fp12_t a)
Copies one Fp12 element.
Parameters
res the destination
a the source
Definition at line 936 of file fp12.c.
References fp4_copy.
void fp12_decompress_std (fp12_t a)
Decompression from Karabina in "Squaring in cyclotomic subgroups".
Warning: zero case probably not tested!! Warning: not side-channel secure
Parameters
a
Definition at line 170 of file fp12.c.
References bi_compare, bi_zero, fp2_add, fp2_dbl, fp2_inv, fp2_mul, fp2_mul_qnr, fp2_sqr, fp2_sub, and FP_ONE.
void fp12_exp_cyclotomic_masked_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation in the cyclotomic subgroup of Fp12.
The exponentiation uses masking mechanisms that counteract timing attacks. WARNING: this masking mechanism makes some trouble on some architectures. An array indexing approach would fix this!
Parameters
res the result
a the operand a
b the exponent b
Definition at line 502 of file fp12.c.
References bi_get_msb, bi_test_bit, fp12_mul, fp12_sqr_cyclotomic, fp2_clear, fp4_clear, fp_clear, fp_copy, and FP_ONE.
void fp12_exp_cyclotomic_montyladder_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation in the cyclotomic subgroup of Fp12.
The exponentiation uses a Montgomery ladder to prevent timing, SPA, and some fault attacks.
Parameters
res the result
a the operand a
b the exponent b
Definition at line 530 of file fp12.c.
References bi_get_msb, bi_test_bit, fp12_copy, fp12_mul, fp12_sqr_cyclotomic, fp2_clear, fp4_clear, fp_clear, fp_copy, and FP_ONE.
void fp12_exp_cyclotomic_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation in the cyclotomic subgroup of Fp12, which is not secured against any attack, but uses dummy operations.
Parameters
res the result
a the operand a
b the exponent b
Definition at line 563 of file fp12.c.
References bi_get_msb, bi_test_bit, fp12_mul, fp12_sqr_cyclotomic, fp2_clear, fp4_clear, fp_clear, fp_copy, and FP_ONE.
void fp12_exp_masked_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation of elements in Fp12.
The exponentiation uses masking mechanisms that counteract timing attacks. WARNING: this masking mechanism makes some trouble on some architectures. An array indexing approach would fix this!
Parameters
res the result
a the operand a
b the exponent b
Definition at line 626 of file fp12.c.
References bi_get_msb, bi_test_bit, fp12_mul, fp12_sqr, fp2_clear, fp4_clear, fp_clear, fp_copy, and FP_ONE.
void fp12_exp_montyladder_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation of elements in Fp12.
The exponentiation uses a Montgomery ladder to prevent timing, SPA, and some fault attacks.
Parameters
res the result
a the operand a
b the exponent b
Definition at line 591 of file fp12.c.
References bi_get_msb, bi_test_bit, fp12_copy, fp12_mul, fp12_sqr, fp2_clear, fp4_clear, fp_clear, fp_copy, and FP_ONE.
void fp12_exp_std (fp12_t res, const fp12_t a, const bigint_t b)
Exponentiation of elements in Fp12, which is not secured against any attack, but uses dummy operations.
Parameters
res the result
a the operand a
b the exponent b
Definition at line 654 of file fp12.c.
References bi_get_msb, bi_test_bit, fp12_mul, fp12_sqr, fp2_clear, fp4_clear, fp_clear, fp_copy, and FP_ONE.
Referenced by hwang_verify().
void fp12_final_exp_bn254 (fp12_t res, const fp12_t a, const bigint_t b)
Performs an exponentiation involved in the final exponentiation of the pairing.
It is specialized for BN254, i.e. the exponent is always 2^62+2^55+1 Must NOT be used with Fuentes final exponentiation method as memory locations would overlap and cause failure.
Parameters
res the result of the exponentiation
a the value to be exponentiated
b the exponent
Definition at line 685 of file fp12.c.
References fp12_decompress, fp12_mul, fp12_sqr_cyclotomic, and fp12_sqr_cyclotomic_compressed().
void fp12_final_exp_std (fp12_t res, const fp12_t a, const bigint_t b)
Performs an exponentiation involved in the final exponentiation of the pairing.
The exponent is a constant, therefore it is safe to skip the side-channel dummy or a Montgomery ladder implementation. WARNING: To safe memory, the parameter a must not overlap with the result.
Parameters
res the result of the exponentiation
a the value to be exponentiated
b the exponent
Definition at line 717 of file fp12.c.
References bi_get_msb, bi_test_bit, fp12_mul, fp12_sqr_cyclotomic, fp2_clear, fp4_clear, fp_clear, fp_copy, and FP_ONE.
void fp12_final_mulexp_std (fp12_t res, fp12_t a, const bigint_t b)
Exponentiates a by b and directly multiplies the result with the result.
This function is intended to be used from within the final exponentiation of the pairing calculation and can help to reduce memory requirements. The exponent is known beforehand and hence we do not need care about side-channel resistance. WARNING: res and a must not overlap.
Parameters
res
a
b
Definition at line 746 of file fp12.c.
References bi_get_msb, bi_test_bit, fp12_mul, and fp12_sqr_cyclotomic.
void fp12_frobenius_map_precomp_std (fp12_t res, const fp12_t a, const word_t i)
Computes the frobenius map of an element in Fp12.
The function uses precomputed roots of the quadratic non-residue in Fp2.
Parameters
res the result of the frobenius map
a the input element
i the order of frobenius
Definition at line 815 of file fp12.c.
References fp2_frobenius_map, fp2_mul, and ROOT_RESIDUE_FP4.
void fp12_frobenius_map_std (fp12_t res, const fp12_t a, const word_t i)
Computes the frobenius map of an element in Fp12.
The function computes everything from scratch.
Parameters
res the result of the frobenius map
a the input element
i the order of frobenius
Definition at line 848 of file fp12.c.
References bi_copy, bi_div3, bi_one, bi_shift_right_one, bi_subtract, fp2_clear, fp2_exp, fp2_frobenius_map, fp2_mul, fp2_mul_qnr, fp2_sqr, and PRIME_P.
void fp12_from_montgomery_std (fp12_t res, const fp12_t a)
Converts an element in Fp12 (Montgomery domain) back to normal.
Parameters
res the resulting normal value
a the value in Montgomery domain to be converted back
Definition at line 971 of file fp12.c.
References fp2_from_montgomery.
void fp12_hlv_std (fp12_t res, const fp12_t a)
Halves one element in Fp12.
Parameters
res the destination for the result
a the value to be halved
Definition at line 82 of file fp12.c.
References fp4_hlv.
void fp12_inv_std (fp12_t res, const fp12_t a)
Inversion of an element in Fp12 using direct inversion formulas.
Parameters
res the resulting inverse
a the element to be inverted
Definition at line 760 of file fp12.c.
References fp4_add, fp4_inv, fp4_mul, fp4_mul_adj_root, fp4_sqr, and fp4_sub.
void fp12_mul_sparse_std (fp12_t res, const fp12_t a, const fp4_t b0, const fp2_t b10)
Performs a multiplication of one element in Fp12 with a sparse element in Fp12.
Parameters
res the resulting product
a the non-sparse operand
b0 Fp4 part of the sparse operand (least significant Fp4 element)
b10 Fp2 part of the sparse operand (least significant Fp2 element of the second Fp4 element)
Definition at line 95 of file fp12.c.
References fp2_add, fp2_copy, fp4_add, fp4_copy, fp4_mul, fp4_mul_adj_root, fp4_mulfp2, and fp4_sub.
void fp12_mul_std (fp12_t res, const fp12_t a, const fp12_t b)
Simple multiplication in Fp12 using an extended Karatsuba method.
Parameters
res the resulting product
a the first operand
b the second operand
Definition at line 323 of file fp12.c.
References fp4_add, fp4_copy, fp4_mul, fp4_mul_adj_root, and fp4_sub.
Referenced by hwang_verify().
void fp12_mul_tk3_std (fp12_t res, const fp12_t a, const fp12_t b)
Multiplication based on the Toom-Cook Method, but with the result being factored by 6.
Can be used in the pairing process during the Miller loops since constant multiples vanish in the final exponentiation.
Parameters
res the resulting product
a the operand a
b the operand b
Definition at line 426 of file fp12.c.
References fp4_add, fp4_dbl, fp4_mul, fp4_mul_adj_root, and fp4_sub.
void fp12_neg_std (fp12_t res, const fp12_t a)
Negates one element in Fp12.
Parameters
res the destination of the negative a
a the value to be negated
Definition at line 71 of file fp12.c.
References fp4_neg.
void fp12_rdc_std (fp12_t a)
Reduces an element in Fp12 with the fixed modulus.
Parameters
a the operand
Definition at line 946 of file fp12.c.
References fp4_rdc.
void fp12_sqr_cyclotomic_compressed (fp12_t res, const fp12_t a)
Compressed squaring as presented by Karabina in "Squaring in Cyclotomic Subgroups".
Parameters
res
a
Definition at line 223 of file fp12.c.
References fp2_add, fp2_dbl, fp2_mul, fp2_mul_qnr, and fp2_sub.
Referenced by fp12_final_exp_bn254().
void fp12_sqr_cyclotomic_std (fp12_t res, const fp12_t a)
Squares one element of cyclotomic subgroup in Fp12.
Uses the specialized formulas by Granger and Scott.
Parameters
res the destination for the result
a the element to be squared
Definition at line 271 of file fp12.c.
References fp2_add, fp2_dbl, fp2_mul_qnr, fp2_neg, and fp4_sqr.
void fp12_sqr_std (fp12_t res, const fp12_t a)
Squares one element in Fp12.
Uses the complex squaring by Chung-Hasan.
Parameters
res the destination for the result
a the element to be squared
Definition at line 129 of file fp12.c.
References fp4_add, fp4_dbl, fp4_hlv, fp4_mul, fp4_mul_adj_root, fp4_sqr, and fp4_sub.
void fp12_sub_std (fp12_t res, const fp12_t a, const fp12_t b)
Subtracts two elements in Fp12.
Parameters
res the destination of the sum
a first operand
b second operand
Definition at line 60 of file fp12.c.
References fp4_sub.
void fp12_to_montgomery_std (fp12_t res, const fp12_t a)
Converts an element in Fp12 to the Montgomery domain.
Parameters
res the resulting value in Montgomery form
a the value to be converted
Definition at line 957 of file fp12.c.
References fp2_to_montgomery.