Pairings: /home/work/workspace/bipair_in_c/include/gss/gss_hwang.h File Reference
gss_hwang.h File Reference
#include "types.h"
#include "ec/ec.h"
Data Structures
struct hwang_signing_key_s
Private signing key.
struct hwang_signature_s
Resulting group signature.
struct hwang_public_parameters_s
Public parameters.
Macros
#define DEBUG_PRINT 1
#define PRINT_BIGINT(TAG, num) print(TAG); print_value(num, BI_WORDS); print("\n");
Print a bigint_t variable.
#define PRINT_G1(TAG, g1)
Print an element in {G}_1.
#define PRINT_G2(TAG, g2)
Print an element in {G}_2.
#define PRINT_GT(TAG, gt)
Print an element in {G}_T.
Typedefs
typedef struct hwang_signing_key_s hwang_signing_key
typedef struct
hwang_signing_key_s * hwang_signing_key_ptr
typedef struct hwang_signature_s hwang_signature
typedef struct hwang_signature_s * hwang_signature_ptr
typedef struct
hwang_public_parameters_s hwang_public_parameters
typedef struct
hwang_public_parameters_s * hwang_public_parameters_ptr
Functions
sbyte hwang_sign (hwang_signature_ptr sig, hwang_public_parameters_ptr data, hwang_signing_key_ptr usk)
Generates a signature according to the scheme of HWANG.
Macro Definition Documentation
#define DEBUG_PRINT 1
Definition at line 42 of file gss_hwang.h.
#define PRINT_BIGINT (TAG, num) print(TAG); print_value(num, BI_WORDS); print("\n");
Print a bigint_t variable.
Definition at line 45 of file gss_hwang.h.
Referenced by hwang_generate_usk(), hwang_init_parameters(), hwang_sign(), and hwang_verify().
#define PRINT_G1 (TAG, g1)
Value:
print(TAG); print("\n"); \
          print("   x: "); print_value(g1.x, FP_WORDS); print("\n"); \
          print("   y: "); print_value(g1.y, FP_WORDS); print("\n");
Print an element in {G}_1.
Definition at line 49 of file gss_hwang.h.
Referenced by hwang_generate_usk(), hwang_init_parameters(), hwang_sign(), and hwang_verify().
#define PRINT_G2 (TAG, g2)
Value:
print(TAG); print("\n"); \
          print("   x[0]: "); print_value(g2.x[0], FP_WORDS); print("\n"); \
          print("   x[1]: "); print_value(g2.x[1], FP_WORDS); print("\n"); \
          print("   y[0]: "); print_value(g2.y[0], FP_WORDS); print("\n"); \
          print("   y[1]: "); print_value(g2.y[1], FP_WORDS); print("\n");
Print an element in {G}_2.
Definition at line 55 of file gss_hwang.h.
Referenced by hwang_init_parameters().
#define PRINT_GT (TAG, gt)
Value:
print(TAG); print("\n"); \
         print("   0 0 0 "); print_value(R_2[0][0][0], FP_WORDS); print("\n"); \
         print("   0 0 1 "); print_value(R_2[0][0][1], FP_WORDS); print("\n"); \
         print("   0 1 0 "); print_value(R_2[0][1][0], FP_WORDS); print("\n"); \
         print("   0 1 1 "); print_value(R_2[0][1][1], FP_WORDS); print("\n"); \
         print("   1 0 0 "); print_value(R_2[1][0][0], FP_WORDS); print("\n"); \
         print("   1 0 1 "); print_value(R_2[1][0][1], FP_WORDS); print("\n"); \
         print("   1 1 0 "); print_value(R_2[1][1][0], FP_WORDS); print("\n"); \
         print("   1 1 1 "); print_value(R_2[1][1][1], FP_WORDS); print("\n"); \
         print("   2 0 0 "); print_value(R_2[2][0][0], FP_WORDS); print("\n"); \
         print("   2 0 1 "); print_value(R_2[2][0][1], FP_WORDS); print("\n"); \
         print("   2 1 0 "); print_value(R_2[2][1][0], FP_WORDS); print("\n"); \
         print("   2 1 1 "); print_value(R_2[2][1][1], FP_WORDS); print("\n"); \
Print an element in {G}_T.
Definition at line 63 of file gss_hwang.h.
Referenced by hwang_sign(), and hwang_verify().
Typedef Documentation
typedef struct hwang_public_parameters_s hwang_public_parameters
Definition at line 106 of file gss_hwang.h.
typedef struct hwang_public_parameters_s* hwang_public_parameters_ptr
Definition at line 107 of file gss_hwang.h.
typedef struct hwang_signature_s hwang_signature
Definition at line 95 of file gss_hwang.h.
typedef struct hwang_signature_s* hwang_signature_ptr
Definition at line 96 of file gss_hwang.h.
typedef struct hwang_signing_key_s hwang_signing_key
Definition at line 85 of file gss_hwang.h.
typedef struct hwang_signing_key_s* hwang_signing_key_ptr
Definition at line 86 of file gss_hwang.h.
Function Documentation
sbyte hwang_sign (hwang_signature_ptr sig, hwang_public_parameters_ptr data, hwang_signing_key_ptr usk)
Generates a signature according to the scheme of HWANG.
Parameters
sig [out] computed signature.
data [in] public data of HWANG scheme.
usk [in] user secret key to generate a valid signature.
Returns
1 on success; -1 on ERROR;
Parameters
sig [out] computed signature.
data [in] public data of HWANG scheme.
usk [in] user secret key to generate a valid signature.
Returns
0 on success; -1 on ERROR;
Definition at line 55 of file gss_hwang.c.
References hwang_signing_key_s::A, bi_add, BI_BYTES, bi_clear_var_std(), bi_compare, bi_copy_var, bi_copy_var_std(), bi_multiply, bi_subtract, bi_subtract_dbl_len, BI_WORDS, bi_zero, hwang_signature_s::c, cprng_get_bytes(), hwang_public_parameters_s::d, hwang_signature_s::D_1, hwang_signature_s::D_2, hwang_signature_s::D_3, EC_PARAM_MU_N, EC_PARAM_N, ecfp_add_affine, ecfp_mul, fp12_mul, fp_rdc_2l_var, fp_rdc_n, hwang_public_parameters_s::g, hwang_public_parameters_s::g2, hwang_public_parameters_s::h1, hwang_public_parameters_s::h_theta, HASH_BYTES, hash_final, hash_init, hash_update, hash_update_G1(), hash_update_GT(), hwang_public_parameters_s::order_p, pbc_map_opt_ate, print(), PRINT_BIGINT, PRINT_G1, PRINT_GT, hwang_signature_s::s_alpha, hwang_signature_s::s_gamma, hwang_signature_s::s_x, hwang_signature_s::s_y, hwang_public_parameters_s::u, hwang_public_parameters_s::w, hwang_signing_key_s::x, hwang_signing_key_s::y, and hwang_signing_key_s::z.
Referenced by main().