Pairings: /home/work/workspace/bipair_in_c/demo/gss_hwang_demo.c File Reference
gss_hwang_demo.c File Reference
#include "pbc/pbc.h"
#include "bigint/bi.h"
#include "types.h"
#include "gss/gss_hwang.h"
#include "hash/hash_function.h"
#include <string.h>
Functions
void hwang_init_parameters (hwang_public_parameters_ptr data)
Initializes the public parameters, the master issuing key (MIK), the master opening key (MOK), and the master linking key (MLK).
void hwang_generate_usk (hwang_signing_key_ptr usk, hwang_public_parameters_ptr data)
Generates a tuple (x, y, z, A) — with x, y, z {Z}_p^* and A {G}_1 — that acts as a user's signing key.
sbyte hwang_verify (hwang_public_parameters_ptr data, hwang_signature_ptr sig)
Verify a group signature.
int main (void)
Function Documentation
void hwang_generate_usk (hwang_signing_key_ptr usk, hwang_public_parameters_ptr data)
Generates a tuple (x, y, z, A) — with x, y, z {Z}_p^* and A {G}_1 — that acts as a user's signing key.
Parameters
usk [out] the generated signing key for one user.
data [in] the public parameters.
Definition at line 109 of file gss_hwang_demo.c.
References hwang_signing_key_s::A, bi_add, BI_BYTES, bi_compare, bi_subtract, BI_WORDS, bi_zero, cprng_get_bytes(), ecfp_add_affine, ecfp_mul, fp_inv_n, fp_rdc_n, hwang_public_parameters_s::g1, hwang_public_parameters_s::g2, hwang_public_parameters_s::order_p, print(), PRINT_BIGINT, PRINT_G1, hwang_public_parameters_s::theta, hwang_public_parameters_s::w, hwang_signing_key_s::x, hwang_signing_key_s::y, and hwang_signing_key_s::z.
Referenced by main().
void hwang_init_parameters (hwang_public_parameters_ptr data)
Initializes the public parameters, the master issuing key (MIK), the master opening key (MOK), and the master linking key (MLK).
Definition at line 47 of file gss_hwang_demo.c.
References BI_BYTES, bi_compare, bi_copy_var_std(), BI_WORDS, bi_zero, cprng_get_bytes(), hwang_public_parameters_s::d, EC_PARAM_N, ecfp2_mul, ecfp2_rand, ecfp_mul, ecfp_rand, fp_rdc_n, hwang_public_parameters_s::g, hwang_public_parameters_s::g1, hwang_public_parameters_s::g2, hwang_public_parameters_s::h1, hwang_public_parameters_s::h_theta, hwang_public_parameters_s::order_p, print(), PRINT_BIGINT, PRINT_G1, PRINT_G2, hwang_public_parameters_s::theta, hwang_public_parameters_s::u, hwang_public_parameters_s::U, and hwang_public_parameters_s::w.
Referenced by main().
sbyte hwang_verify (hwang_public_parameters_ptr data, hwang_signature_ptr sig)
Verify a group signature.
Parameters
data the parameters of the group-signature scheme.
sig the generated signature to be verified.
Returns
1 if the signature is VALID; -1 otherwise.
Definition at line 163 of file gss_hwang_demo.c.
References bi_clear_var_std(), bi_compare, bi_copy_var_std(), bi_subtract, BI_WORDS, hwang_signature_s::c, hwang_public_parameters_s::d, hwang_signature_s::D_1, hwang_signature_s::D_2, hwang_signature_s::D_3, EC_PARAM_MU_N, ecfp_add_affine, ecfp_mul, fp12_exp_std(), fp12_mul_std(), fp_rdc_2l_var, hwang_public_parameters_s::g, hwang_public_parameters_s::g1, hwang_public_parameters_s::g2, hwang_public_parameters_s::h1, hwang_public_parameters_s::h_theta, HASH_BYTES, hash_final, hash_init, hash_update, hash_update_G1(), hash_update_GT(), hwang_public_parameters_s::order_p, pbc_map_opt_ate_div, pbc_map_opt_ate_mul, PRINT_BIGINT, PRINT_G1, PRINT_GT, hwang_signature_s::s_alpha, hwang_signature_s::s_gamma, hwang_signature_s::s_x, hwang_signature_s::s_y, hwang_public_parameters_s::u, and hwang_public_parameters_s::w.
Referenced by main().
int main (void)
Definition at line 263 of file gss_hwang_demo.c.
References hwang_generate_usk(), hwang_init_parameters(), hwang_sign(), hwang_verify(), and print().