Pairings: /home/work/workspace/bipair_in_c/include/hash/Keccak-compact.h File Reference
Keccak-compact.h File Reference
#include "Keccak-compact-settings.h"
Data Structures
struct hashStateStruct
Macros
#define ALIGN
Typedefs
typedef unsigned char BitSequence
typedef unsigned long long DataLength
typedef ALIGN struct
hashStateStruct hashState
Enumerations
enum HashReturn { SUCCESS = 0, FAIL = 1, BAD_HASHLEN = 2 }
Functions
int crypto_hash (unsigned char *out, const unsigned char *in, unsigned long long inlen)
HashReturn Init (hashState *state)
HashReturn Update (hashState *state, const BitSequence *data, DataLength databitlen)
HashReturn Final (hashState *state, BitSequence *hashval, int hashbytelen)
Macro Definition Documentation
#define ALIGN
Definition at line 34 of file Keccak-compact.h.
Typedef Documentation
typedef unsigned char BitSequence
Definition at line 25 of file Keccak-compact.h.
typedef unsigned long long DataLength
Definition at line 26 of file Keccak-compact.h.
typedef ALIGN struct hashStateStruct hashState
Enumeration Type Documentation
enum HashReturn
Enumerator
SUCCESS
FAIL
BAD_HASHLEN
Definition at line 27 of file Keccak-compact.h.
Function Documentation
int crypto_hash (unsigned char * out, const unsigned char * in, unsigned long long inlen)
Definition at line 66 of file Keccak-compact.c.
References cKeccakR_SizeInBytes, crypto_hash_BYTES, KeccakF(), and temp.
HashReturn Final (hashState * state, BitSequence * hashval, int hashbytelen)
Definition at line 289 of file Keccak-compact.c.
References cKeccakR_SizeInBytes, FAIL, KeccakF(), generateMultiplyCaching::offset, and SUCCESS.
HashReturn Init (hashState * state)
Definition at line 239 of file Keccak-compact.c.
References SUCCESS.
HashReturn Update (hashState * state, const BitSequence * data, DataLength databitlen)
Definition at line 248 of file Keccak-compact.c.
References cKeccakR, cKeccakR_SizeInBytes, FAIL, KeccakF(), and SUCCESS.