Pairings: generateMultiplyKaratsuba Namespace Reference
generateMultiplyKaratsuba Namespace Reference
Functions
def highPart
def lowPart
def middlePart
def propagateAccumulator
Variables
int total_words = 8
Function Documentation
def generateMultiplyKaratsuba.highPart (regA, regB, words, offset)
Definition at line 3 of file generateMultiplyKaratsuba.py.
References print().
Referenced by propagateAccumulator().
def generateMultiplyKaratsuba.lowPart (regA, regB, regDst0, regDst1, words, offset)
Definition at line 49 of file generateMultiplyKaratsuba.py.
References print().
Referenced by propagateAccumulator().
def generateMultiplyKaratsuba.middlePart (regA, regB, regAl, regBl, regRes, regCarryA, regCarryB, words, offsetRegA, offsetRegB, offsetHigh)
Definition at line 99 of file generateMultiplyKaratsuba.py.
References print().
Referenced by propagateAccumulator().
def generateMultiplyKaratsuba.propagateAccumulator (regRes, regAl, words, offset16)
Definition at line 134 of file generateMultiplyKaratsuba.py.
References highPart(), lowPart(), middlePart(), and print().
Variable Documentation
int generateMultiplyKaratsuba.total_words = 8
Definition at line 1 of file generateMultiplyKaratsuba.py.