Pairings: generateMultiplyKaratsubaFull Namespace Reference
generateMultiplyKaratsubaFull Namespace Reference
Functions
def highPart
def lowPart
def middlePart
def propagateAccumulator
Variables
int total_words = 4
Function Documentation
def generateMultiplyKaratsubaFull.highPart (regA, regB, regDst, words, offset)
Definition at line 3 of file generateMultiplyKaratsubaFull.py.
References print().
Referenced by propagateAccumulator().
def generateMultiplyKaratsubaFull.lowPart (regA, regB, regDst0, regDst1, words, offset)
Definition at line 56 of file generateMultiplyKaratsubaFull.py.
References print().
Referenced by propagateAccumulator().
def generateMultiplyKaratsubaFull.middlePart (regA, regB, regRes, regCarryA, regCarryB, words, offsetRegA, offsetRegB, offsetHigh)
Definition at line 113 of file generateMultiplyKaratsubaFull.py.
References print().
Referenced by propagateAccumulator().
def generateMultiplyKaratsubaFull.propagateAccumulator (regRes, words, offset)
Definition at line 138 of file generateMultiplyKaratsubaFull.py.
References highPart(), lowPart(), middlePart(), and print().
Variable Documentation
int generateMultiplyKaratsubaFull.total_words = 4
Definition at line 1 of file generateMultiplyKaratsubaFull.py.