Pairings: /home/work/workspace/bipair_in_c/include/pbc/pbc_bn_std.h File Reference
pbc_bn_std.h File Reference
Functions
void pbc_map_opt_ate_std (fp12_t res, ecfp_pt p, ecfp2_pt q)
Optimal Ate Pairing over BN curves.
void pbc_map_opt_ate_optimized_std (fp12_t res, ecfp_pt p, ecfp2_pt q)
Computes an optimal Ate pairing.
void pbc_map_opt_ate_mul_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the product of two optimal Ate pairings.
void pbc_map_opt_ate_div_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the ratio of two optimal Ate pairings.
Function Documentation
void pbc_map_opt_ate_div_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the ratio of two optimal Ate pairings.
Parameters
res the result
p1 elliptic curve point operand of first pairing
q1 elliptic curve point operand (quadratic extension) of first pairing
p2 elliptic curve point operand of second pairing
q2 elliptic curve point operand (quadratic extension) of second pairing
Definition at line 844 of file pbc_bn.c.
References pbc_map_opt_ate_div_miller_std(), pbc_map_opt_ate_optimized_final_exp_easy(), and pbc_map_opt_ate_optimized_final_exp_fuentes().
void pbc_map_opt_ate_mul_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the product of two optimal Ate pairings.
Parameters
res the result
p1 elliptic curve point operand of first pairing
q1 elliptic curve point operand (quadratic extension) of first pairing
p2 elliptic curve point operand of second pairing
q2 elliptic curve point operand (quadratic extension) of second pairing
Definition at line 830 of file pbc_bn.c.
References pbc_map_opt_ate_mul_miller_std(), pbc_map_opt_ate_optimized_final_exp_easy(), and pbc_map_opt_ate_optimized_final_exp_fuentes().
void pbc_map_opt_ate_optimized_std (fp12_t res, ecfp_pt p, ecfp2_pt q)
Computes an optimal Ate pairing.
Parameters
res the result
p elliptic curve point operand of first pairing
q elliptic curve point operand (quadratic extension) of first pairing
Definition at line 816 of file pbc_bn.c.
References pbc_map_opt_ate_optimized_final_exp_easy(), pbc_map_opt_ate_optimized_final_exp_fuentes(), and pbc_map_opt_ate_optimized_miller_std().
void pbc_map_opt_ate_std (fp12_t res, ecfp_pt p, ecfp2_pt q)
Optimal Ate Pairing over BN curves.
WARNING: old implementation with less efficient formulas. Pairing is E(F_p) x E'(F_p2) -> F_p12 E' denotes the sextic twist of the curve E
Definition at line 134 of file pbc_bn.c.
References bi_add_word, bi_get_msb, bi_multiply_word, bi_test_bit, BI_WORDS, EC_PARAM_X, ecfp2_add_proj, ecfp2_dbl_proj, ecfp2_frobenius_map, ecfp2_get_homogeneous_projective, ecfp2_neg_affine, fp12_clear, fp12_exp, fp12_frobenius_map, fp12_inv, fp12_mul, fp12_sqr, ecpoint_fp::infinity, ecpoint_fp2::infinity, OPTATE_LOOP_CONST, pbc_eval_line_function(), and pbc_eval_tangent_function().