Pairings: /home/work/workspace/bipair_in_c/src/base/std/pbc/pbc_bn.c File Reference
pbc_bn.c File Reference
#include "bigint/bi.h"
#include "fp/fp.h"
#include "fp/fp2.h"
#include "fp/fp12.h"
#include "pbc/pbc.h"
#include "ec/ec.h"
#include "param.h"
Functions
void pbc_eval_line_function (fp12_t res, ecfp2_proj_pt a, ecfp2_pt b, ecfp_pt p)
Evaluation of the line function.
void pbc_eval_tangent_function (fp12_t res, ecfp2_proj_pt a, ecfp_pt p)
Evaluation of the tangent line function.
void pbc_map_opt_ate_std (fp12_t res, ecfp_pt p, ecfp2_pt q)
Optimal Ate Pairing over BN curves.
void pbc_point_dbl_line_eval (fp12_t l, ecfp2_proj_pt t, ecfp2_proj_pt q, ecfp_pt p)
Interleaved doubling of an elliptic curve point and evaluation of the tangent line function for computing a pairing.
void pbc_point_dbl_line_costello_eval (fp12_t l, ecfp2_proj_pt t, ecfp2_proj_pt q, ecfp_pt p)
Optimized formulas by Costello that interleave the doubling of an elliptic curve point and the evaluation of the tangent line function for computing a pairing.
void pbc_point_add_line_costello_eval (fp12_t l, ecfp2_proj_pt t, ecfp2_proj_pt r, ecfp2_pt q, ecfp_pt p)
Optimized formulas by Costello that interleave adding two elliptic curve points and evaluation of the line function for computing a pairing.
void pbc_map_opt_ate_optimized_final_exp_easy (fp12_t res)
Calculates the easy part of the final exponentiation involved in the pairing, i.e.
void pbc_map_opt_ate_optimized_final_exp_fuentes (fp12_t res)
Calculates the final exponentiation of the optimal ate pairing (hard part).
void pbc_map_opt_ate_optimized_final_exp_std (fp12_t res, fp12_t a, fp12_t b)
Calculates the final exponentiation of the optimal ate pairing.
void pbc_map_opt_ate_optimized_miller_std (fp12_t res, ecfp_pt p, ecfp2_pt q)
Calculates the miller loop involved in the optimal ate pairing.
void pbc_map_opt_ate_div_miller_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the Miller loop for the ratio of two pairings.
void pbc_map_opt_ate_mul_miller_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the Miller loop for the product of two pairings, which is optimized by interleaving such that the squaring steps are shared.
void pbc_map_opt_ate_optimized_std (fp12_t res, ecfp_pt p, ecfp2_pt q)
Computes an optimal Ate pairing.
void pbc_map_opt_ate_mul_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the product of two optimal Ate pairings.
void pbc_map_opt_ate_div_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the ratio of two optimal Ate pairings.
Function Documentation
void pbc_eval_line_function (fp12_t res, ecfp2_proj_pt a, ecfp2_pt b, ecfp_pt p)
Evaluation of the line function.
Parameters
res the result of the line function evaluation
a the starting point of the line
b the ending point of the line
p the point necessary for evaluation
Definition at line 50 of file pbc_bn.c.
References fp12_clear, fp2_mul, fp2_neg, fp2_sqr, fp2_sub, fp_clear, fp_copy, ecpoint_fp::infinity, ecpoint_fp2::infinity, ecpoint_fp2_proj::infinity, ecpoint_fp::x, ecpoint_fp2::x, ecpoint_fp2_proj::x, ecpoint_fp::y, ecpoint_fp2::y, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.
Referenced by pbc_map_opt_ate_std().
void pbc_eval_tangent_function (fp12_t res, ecfp2_proj_pt a, ecfp_pt p)
Evaluation of the tangent line function.
Parameters
res the result of the line function evaluation
a the point in which the tangent line is placed
p the point necessary for evaluation
Definition at line 92 of file pbc_bn.c.
References fp12_clear, fp2_add, fp2_dbl, fp2_mul, fp2_neg, fp2_sqr, fp2_sub, fp_clear, fp_copy, ecpoint_fp::infinity, ecpoint_fp2_proj::infinity, ecpoint_fp::x, ecpoint_fp2_proj::x, ecpoint_fp::y, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.
Referenced by pbc_map_opt_ate_std().
void pbc_map_opt_ate_div_miller_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the Miller loop for the ratio of two pairings.
Parameters
p1 elliptic curve point operand of first pairing
q1 elliptic curve point operand (quadratic extension) of first pairing
p2 elliptic curve point operand of second pairing
q2 elliptic curve point operand (quadratic extension) of second pairing
Definition at line 629 of file pbc_bn.c.
References bi_add_word, bi_get_msb, bi_multiply_word, bi_subtract_word, bi_test_bit, BI_WORDS, EC_PARAM_X, ecfp2_frobenius_map, ecfp2_get_homogeneous_projective, ecfp2_neg_affine, ecfp2_neg_proj, fp12_clear, fp12_conjugate, fp12_inv, fp12_mul_mloop, fp12_mul_sparse, fp12_sqr, ecpoint_fp::infinity, ecpoint_fp2::infinity, OPTATE_LOOP_CONST, pbc_point_add_line_costello_eval(), and pbc_point_dbl_line_costello_eval().
Referenced by pbc_map_opt_ate_div_std().
void pbc_map_opt_ate_div_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the ratio of two optimal Ate pairings.
Parameters
res the result
p1 elliptic curve point operand of first pairing
q1 elliptic curve point operand (quadratic extension) of first pairing
p2 elliptic curve point operand of second pairing
q2 elliptic curve point operand (quadratic extension) of second pairing
Definition at line 844 of file pbc_bn.c.
References pbc_map_opt_ate_div_miller_std(), pbc_map_opt_ate_optimized_final_exp_easy(), and pbc_map_opt_ate_optimized_final_exp_fuentes().
void pbc_map_opt_ate_mul_miller_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the Miller loop for the product of two pairings, which is optimized by interleaving such that the squaring steps are shared.
Parameters
res the result of the Miller loop
p1 elliptic curve point operand of first pairing
q1 elliptic curve point operand (quadratic extension) of first pairing
p2 elliptic curve point operand of second pairing
q2 elliptic curve point operand (quadratic extension) of second pairing
Definition at line 731 of file pbc_bn.c.
References bi_add_word, bi_get_msb, bi_multiply_word, bi_subtract_word, bi_test_bit, BI_WORDS, EC_PARAM_X, ecfp2_frobenius_map, ecfp2_get_homogeneous_projective, ecfp2_neg_affine, ecfp2_neg_proj, fp12_clear, fp12_conjugate, fp12_mul_mloop, fp12_mul_sparse, fp12_sqr, ecpoint_fp::infinity, ecpoint_fp2::infinity, OPTATE_LOOP_CONST, pbc_point_add_line_costello_eval(), and pbc_point_dbl_line_costello_eval().
Referenced by pbc_map_opt_ate_mul_std().
void pbc_map_opt_ate_mul_std (fp12_t res, ecfp_pt p1, ecfp2_pt q1, ecfp_pt p2, ecfp2_pt q2)
Computes the product of two optimal Ate pairings.
Parameters
res the result
p1 elliptic curve point operand of first pairing
q1 elliptic curve point operand (quadratic extension) of first pairing
p2 elliptic curve point operand of second pairing
q2 elliptic curve point operand (quadratic extension) of second pairing
Definition at line 830 of file pbc_bn.c.
References pbc_map_opt_ate_mul_miller_std(), pbc_map_opt_ate_optimized_final_exp_easy(), and pbc_map_opt_ate_optimized_final_exp_fuentes().
void pbc_map_opt_ate_optimized_final_exp_easy (fp12_t res)
Calculates the easy part of the final exponentiation involved in the pairing, i.e.
res^{(p^6-1)(p^2+1)}.
Parameters
res
Definition at line 423 of file pbc_bn.c.
References fp12_conjugate, fp12_frobenius_map, fp12_inv, and fp12_mul.
Referenced by pbc_map_opt_ate_div_std(), pbc_map_opt_ate_mul_std(), and pbc_map_opt_ate_optimized_std().
void pbc_map_opt_ate_optimized_final_exp_fuentes (fp12_t res)
Calculates the final exponentiation of the optimal ate pairing (hard part).
It calculates a fixed multiple of the actual pairing, which is a valid thing to do. It is a modified version from the final exponentiation presented by Fuentes-Castaneda which takes one more frobenius action and one more multiplication but saves one temporary variable.
Parameters
res both the input and the output to this exponentiation
a a temporary variable (reuse of memory)
b a temporary variable (reuse of memory)
Definition at line 443 of file pbc_bn.c.
References EC_PARAM_X, fp12_conjugate, fp12_final_exp, fp12_final_mulexp, fp12_frobenius_map, fp12_mul, and fp12_sqr_cyclotomic.
Referenced by pbc_map_opt_ate_div_std(), pbc_map_opt_ate_mul_std(), and pbc_map_opt_ate_optimized_std().
void pbc_map_opt_ate_optimized_final_exp_std (fp12_t res, fp12_t a, fp12_t b)
Calculates the final exponentiation of the optimal ate pairing.
(as presented by Scott).
Parameters
res both the input and the output to this exponentiation
a a temporary variable (reuse of memory)
b a temporary variable (reuse of memory)
Definition at line 489 of file pbc_bn.c.
References EC_PARAM_X, fp12_conjugate, fp12_final_exp, fp12_frobenius_map, fp12_inv, fp12_mul, and fp12_sqr_cyclotomic.
void pbc_map_opt_ate_optimized_miller_std (fp12_t res, ecfp_pt p, ecfp2_pt q)
Calculates the miller loop involved in the optimal ate pairing.
Parameters
res the resulting point
p point from G1 (elliptic curve over prime field)
q point from G2 (twisted curve over quadratic extension of prime field)
Definition at line 564 of file pbc_bn.c.
References bi_add_word, bi_get_msb, bi_multiply_word, bi_subtract_word, bi_test_bit, BI_WORDS, EC_PARAM_X, ecfp2_frobenius_map, ecfp2_get_homogeneous_projective, ecfp2_neg_affine, ecfp2_neg_proj, fp12_clear, fp12_conjugate, fp12_mul_mloop, fp12_mul_sparse, fp12_sqr, ecpoint_fp::infinity, ecpoint_fp2::infinity, OPTATE_LOOP_CONST, pbc_point_add_line_costello_eval(), and pbc_point_dbl_line_costello_eval().
Referenced by pbc_map_opt_ate_optimized_std().
void pbc_map_opt_ate_optimized_std (fp12_t res, ecfp_pt p, ecfp2_pt q)
Computes an optimal Ate pairing.
Parameters
res the result
p elliptic curve point operand of first pairing
q elliptic curve point operand (quadratic extension) of first pairing
Definition at line 816 of file pbc_bn.c.
References pbc_map_opt_ate_optimized_final_exp_easy(), pbc_map_opt_ate_optimized_final_exp_fuentes(), and pbc_map_opt_ate_optimized_miller_std().
void pbc_map_opt_ate_std (fp12_t res, ecfp_pt p, ecfp2_pt q)
Optimal Ate Pairing over BN curves.
WARNING: old implementation with less efficient formulas. Pairing is E(F_p) x E'(F_p2) -> F_p12 E' denotes the sextic twist of the curve E
Definition at line 134 of file pbc_bn.c.
References bi_add_word, bi_get_msb, bi_multiply_word, bi_test_bit, BI_WORDS, EC_PARAM_X, ecfp2_add_proj, ecfp2_dbl_proj, ecfp2_frobenius_map, ecfp2_get_homogeneous_projective, ecfp2_neg_affine, fp12_clear, fp12_exp, fp12_frobenius_map, fp12_inv, fp12_mul, fp12_sqr, ecpoint_fp::infinity, ecpoint_fp2::infinity, OPTATE_LOOP_CONST, pbc_eval_line_function(), and pbc_eval_tangent_function().
void pbc_point_add_line_costello_eval (fp12_t l, ecfp2_proj_pt t, ecfp2_proj_pt r, ecfp2_pt q, ecfp_pt p)
Optimized formulas by Costello that interleave adding two elliptic curve points and evaluation of the line function for computing a pairing.
Parameters
l the result of the line function evaluation
t the intermediate elliptic curve point that is updated
r the projective point to be added
q the affine point to be added
p the point necessary for line function evaluation
Definition at line 378 of file pbc_bn.c.
References fp2_add, fp2_dbl, fp2_mul, fp2_mulfp, fp2_neg, fp2_sqr, fp2_sub, ecpoint_fp::x, ecpoint_fp2::x, ecpoint_fp2_proj::x, ecpoint_fp::y, ecpoint_fp2::y, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.
Referenced by pbc_map_opt_ate_div_miller_std(), pbc_map_opt_ate_mul_miller_std(), and pbc_map_opt_ate_optimized_miller_std().
void pbc_point_dbl_line_costello_eval (fp12_t l, ecfp2_proj_pt t, ecfp2_proj_pt q, ecfp_pt p)
Optimized formulas by Costello that interleave the doubling of an elliptic curve point and the evaluation of the tangent line function for computing a pairing.
Parameters
l the result of the tangent line function evaluation
t the intermediate elliptic curve point that is updated
q the projective point to be doubled
p the point necessary for line function evaluation
Definition at line 314 of file pbc_bn.c.
References EC_PARAM_B, fp2_add, fp2_dbl, fp2_div_qnr, fp2_mul, fp2_mulfp, fp2_neg, fp2_sqr, fp2_sub, ecpoint_fp::x, ecpoint_fp2_proj::x, ecpoint_fp::y, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.
Referenced by pbc_map_opt_ate_div_miller_std(), pbc_map_opt_ate_mul_miller_std(), and pbc_map_opt_ate_optimized_miller_std().
void pbc_point_dbl_line_eval (fp12_t l, ecfp2_proj_pt t, ecfp2_proj_pt q, ecfp_pt p)
Interleaved doubling of an elliptic curve point and evaluation of the tangent line function for computing a pairing.
Parameters
l the result of the tangent line function evaluation
t the intermediate elliptic curve point that is updated
q the projective point to be doubled
p the point necessary for line function evaluation
Definition at line 256 of file pbc_bn.c.
References fp2_add, fp2_copy, fp2_dbl, fp2_hlv, fp2_mul, fp2_mulfp, fp2_neg, fp2_sqr, fp2_sub, ecpoint_fp::x, ecpoint_fp2_proj::x, ecpoint_fp::y, ecpoint_fp2_proj::y, and ecpoint_fp2_proj::z.