Pairings: /home/work/workspace/bipair_in_c/include/rand.h File Reference
rand.h File Reference
Functions
void cprng_get_bytes (void *buf, length_t size)
Returns the specified number of bytes in the buffer.
Function Documentation
void cprng_get_bytes (void * buffer, length_t size)
Returns the specified number of bytes in the buffer.
Parameters
buf the buffer to filled with random bytes
size number of random bytes to generate
Returns the specified number of bytes in the buffer.
Parameters
buffer the buffer to be filled with random bytes
size the size of the buffer in byte
Definition at line 64 of file rand.c.
References cprng_one_way_func(), CPRNG_SIZE, CPRNGState, and HASH_LEN.
Referenced by ecfp2_get_homogeneous_projective_rnd_std(), ecfp2_get_jacobian_projective_rnd_std(), ecfp2_mul_montyladder_std(), ecfp2_rand_std(), ecfp_get_jacobian_projective_rnd_std(), ecfp_mul_montyladder_std(), ecfp_rand_std(), encapsulate_key(), hwang_generate_usk(), hwang_init_parameters(), and hwang_sign().