Pairings: /home/work/workspace/bipair_in_c/src/rand.c File Reference
rand.c File Reference
#include "hash/sha1.h"
#include "types.h"
Macros
#define CPRNG_SIZE 20
#define HASH_LEN 20
Functions
void cprng_one_way_func (byte *hash, byte *msg, length_t len)
One-way function used to create CPRNG.
void cprng_get_bytes (void *buffer, length_t size)
Cryptographically secure pseudo-random number generator based on FIPS186-2 standard.
Variables
byte CPRNGState [CPRNG_SIZE]
Macro Definition Documentation
#define CPRNG_SIZE 20
Definition at line 38 of file rand.c.
Referenced by cprng_get_bytes().
#define HASH_LEN 20
Definition at line 39 of file rand.c.
Referenced by cprng_get_bytes().
Function Documentation
void cprng_get_bytes (void * buffer, length_t size)
Cryptographically secure pseudo-random number generator based on FIPS186-2 standard.
Returns the specified number of bytes in the buffer.
Parameters
buffer the buffer to be filled with random bytes
size the size of the buffer in byte
Definition at line 64 of file rand.c.
References cprng_one_way_func(), CPRNG_SIZE, CPRNGState, and HASH_LEN.
Referenced by ecfp2_get_homogeneous_projective_rnd_std(), ecfp2_get_jacobian_projective_rnd_std(), ecfp2_mul_montyladder_std(), ecfp2_rand_std(), ecfp_get_jacobian_projective_rnd_std(), ecfp_mul_montyladder_std(), ecfp_rand_std(), encapsulate_key(), hwang_generate_usk(), hwang_init_parameters(), and hwang_sign().
void cprng_one_way_func (byte * hash, byte * msg, length_t len)
One-way function used to create CPRNG.
Delegates to SHA-1.
Parameters
hash the hash resulting from the one-way function
msg the message to be hashed
len the length of the message
Definition at line 51 of file rand.c.
References sha1_init_state(), sha1_process_message_final(), and sha1_state_to_byte_array().
Referenced by cprng_get_bytes().
Variable Documentation
byte CPRNGState[CPRNG_SIZE]
Definition at line 42 of file rand.c.
Referenced by cprng_get_bytes().