Pairings: /home/work/workspace/bipair_in_c/include/sdh/sdh_zk.h File Reference
sdh_zk.h File Reference
#include "types.h"
#include "ec/ec.h"
Data Structures
struct group_public_key_s
struct group_secret_key_s
struct group_master_secret_key_s
struct sdh_signiture_s
Typedefs
typedef struct group_public_key_s group_public_key
typedef struct group_secret_key_s group_secret_key
typedef struct
group_master_secret_key_s group_master_secret_key
typedef struct sdh_signiture_s sdh_signiture
Functions
void sgs_init (length_t number_of_members, group_public_key *gpk, group_master_secret_key *gmsk, group_secret_key *gsk)
Generates the keys according to the scheme of short group signature.
void sgs_sign (group_public_key gpk, group_secret_key gsk, sdh_signiture *sig, const char *message)
Generates a signature according to the scheme of short group signature.
sbyte sgs_verify (group_public_key gpk, sdh_signiture sig, const char *message)
Verifies a signature according to the scheme of short group signature.
void sgs_open (group_master_secret_key gmsk, sdh_signiture sig, ecpoint_fp *A)
Trace a signature to a signer.
Typedef Documentation
typedef struct group_master_secret_key_s group_master_secret_key
Definition at line 63 of file sdh_zk.h.
typedef struct group_public_key_s group_public_key
Definition at line 61 of file sdh_zk.h.
typedef struct group_secret_key_s group_secret_key
Definition at line 62 of file sdh_zk.h.
typedef struct sdh_signiture_s sdh_signiture
Definition at line 64 of file sdh_zk.h.
Function Documentation
void sgs_init (length_t number_of_members, group_public_key * gpk, group_master_secret_key * gmsk, group_secret_key * gsk)
Generates the keys according to the scheme of short group signature.
Parameters
number_of_members [in] number of secret keys that should be generated.
gpk [out] public key of sgs scheme.
gsk [out] different user secret keys to generate a valid signatures.
gmsk [out] group master secret key to trace a valid signature.
Definition at line 53 of file sdh_zk.c.
References bi_add, BI_BYTES, bi_compare, bi_one, BI_WORDS, bi_zero, cprng_get_bytes(), ecfp2_copy_std(), ECFP2_GENERATOR, ecfp2_mul, ecfp_copy_std(), ECFP_GENERATOR, ecfp_mul, fp_inv_n, fp_rdc_n, group_public_key_s::g1, group_public_key_s::g2, group_public_key_s::h, print(), print_value(), group_public_key_s::u, group_public_key_s::v, group_public_key_s::w, ecpoint_fp::x, ecpoint_fp2::x, group_master_secret_key_s::xi1, group_master_secret_key_s::xi2, ecpoint_fp::y, and ecpoint_fp2::y.
Referenced by main().
void sgs_open (group_master_secret_key gmsk, sdh_signiture sig, ecpoint_fp * A)
Trace a signature to a signer.
Parameters
gmsk [in] group master secret key to trace a valid signature.
sig [in] computed signature.
A [in] part of user secret key.
Definition at line 405 of file sdh_zk.c.
References ecfp_add_affine, ecfp_mul, ecfp_neg_affine, sdh_signiture_s::T_1, sdh_signiture_s::T_2, sdh_signiture_s::T_3, group_master_secret_key_s::xi1, and group_master_secret_key_s::xi2.
Referenced by main().
void sgs_sign (group_public_key gpk, group_secret_key gsk, sdh_signiture * sig, const char * message)
Generates a signature according to the scheme of short group signature.
Parameters
gpk [in] public key of sgs scheme.
gsk [in] user secret key to generate a valid signature.
sig [out] computed signature.
message [in] the message for signature generation .
Definition at line 127 of file sdh_zk.c.
References group_secret_key_s::A, bi_add, BI_BYTES, bi_clear_var_std(), bi_compare, bi_copy_var_std(), bi_multiply, bi_subtract, BI_WORDS, bi_zero, sdh_signiture_s::c, cprng_get_bytes(), EC_PARAM_MU_N, EC_PARAM_N, ecfp_add_affine, ecfp_mul, fp12_mul, fp_rdc_2l_var, fp_rdc_n, group_public_key_s::g2, group_public_key_s::h, HASH_BYTES, hash_final, hash_init, hash_update_G1(), hash_update_GT(), hash_update_message(), pbc_map_opt_ate, sdh_signiture_s::s_alpha, sdh_signiture_s::s_beta, sdh_signiture_s::s_delta1, sdh_signiture_s::s_delta2, sdh_signiture_s::s_x, sdh_signiture_s::T_1, sdh_signiture_s::T_2, sdh_signiture_s::T_3, group_public_key_s::u, group_public_key_s::v, group_public_key_s::w, and group_secret_key_s::x.
Referenced by main().
sbyte sgs_verify (group_public_key gpk, sdh_signiture sig, const char * message)
Verifies a signature according to the scheme of short group signature.
Parameters
gpk [in] public key of sgs scheme.
sig [in] computed signature.
message [in] the message for signature generation .
Returns
0 on valid signature; -1 on invalid signature;
Definition at line 292 of file sdh_zk.c.
References bi_add, bi_clear_var_std(), bi_copy_var_std(), bi_subtract, BI_WORDS, sdh_signiture_s::c, EC_PARAM_MU_N, EC_PARAM_N, ecfp_add_affine, ecfp_mul, fp12_inv, fp12_mul_std(), fp_rdc_2l_var, fp_rdc_n, group_public_key_s::g1, group_public_key_s::g2, group_public_key_s::h, HASH_BYTES, hash_final, hash_init, hash_update_G1(), hash_update_GT(), hash_update_message(), pbc_map_opt_ate, sdh_signiture_s::s_alpha, sdh_signiture_s::s_beta, sdh_signiture_s::s_delta1, sdh_signiture_s::s_delta2, sdh_signiture_s::s_x, sdh_signiture_s::T_1, sdh_signiture_s::T_2, sdh_signiture_s::T_3, group_public_key_s::u, group_public_key_s::v, and group_public_key_s::w.
Referenced by main().