Pairings: /home/work/workspace/bipair_in_c/src/hash/sha1.c File Reference
sha1.c File Reference
#include <stdint.h>
#include <string.h>
#include "types.h"
#include "hash/sha1.h"
Macros
#define leftrotate(value, bits) (((value) << (bits)) | ((value) >> (32 - (bits))))
Functions
void sha1_hash (word_t *result, const uint8_t *message, uint32_t length)
Performs a SHA1 hash calculation.
void sha1_init_state (HASH_SHA1 *state)
Initialize the state variable.
void sha1_process_block (HASH_SHA1 *state, uint32_t *w)
Process a 512-bit block (w) to update the current hash state.
void sha1_process_message (HASH_SHA1 *state, const uint8_t *message)
Converts the message to a block and calls sha1_process_block.
void sha1_process_message_final (HASH_SHA1 *state, const uint8_t *message, uint32_t remaining_length, uint32_t total_length)
Finalizes the sha1 hash calculation.
void sha1_state_to_byte_array (HASH_SHA1 *state, uint8_t *message)
Converts the resulted hash state to a uint8_t* message.
void sha1_state_to_bigint (HASH_SHA1 *state, word_t *result)
Converts the given hash (state) to a big integer.
Variables
const uint32_t H0_ROM = 0x67452301
const uint32_t H1_ROM = 0xEFCDAB89
const uint32_t H2_ROM = 0x98BADCFE
const uint32_t H3_ROM = 0x10325476
const uint32_t H4_ROM = 0xC3D2E1F0
Macro Definition Documentation
#define leftrotate (value, bits) (((value) << (bits)) | ((value) >> (32 - (bits))))
Definition at line 47 of file sha1.c.
Referenced by sha1_process_block().
Function Documentation
void sha1_hash (word_t * result, const uint8_t * message, uint32_t length)
Performs a SHA1 hash calculation.
Parameters
result the resulting big integer to be used by e.g. ECDSA
message the message to be hashed
length the number of bytes to be hashed
Definition at line 55 of file sha1.c.
References sha1_init_state(), sha1_process_message_final(), and sha1_state_to_bigint().
void sha1_init_state (HASH_SHA1 * state)
Initialize the state variable.
Parameters
state the state to initialize
Definition at line 66 of file sha1.c.
References HASH_SHA1_::H0, H0_ROM, HASH_SHA1_::H1, H1_ROM, HASH_SHA1_::H2, H2_ROM, HASH_SHA1_::H3, H3_ROM, HASH_SHA1_::H4, and H4_ROM.
Referenced by cprng_one_way_func(), and sha1_hash().
void sha1_process_block (HASH_SHA1 * state, uint32_t * w)
Process a 512-bit block (w) to update the current hash state.
Parameters
state the hash state to update
w already prepared uint32_t[16] array used to update the state (is overwritten during the calculation)
Definition at line 79 of file sha1.c.
References HASH_SHA1_::H0, HASH_SHA1_::H1, HASH_SHA1_::H2, HASH_SHA1_::H3, HASH_SHA1_::H4, and leftrotate.
Referenced by sha1_process_message(), and sha1_process_message_final().
void sha1_process_message (HASH_SHA1 * state, const uint8_t * message)
Converts the message to a block and calls sha1_process_block.
Parameters
state
message
Definition at line 131 of file sha1.c.
References sha1_process_block(), and temp.
void sha1_process_message_final (HASH_SHA1 * state, const uint8_t * message, uint32_t remaining_length, uint32_t total_length)
Finalizes the sha1 hash calculation.
Parameters
state the current state of the hash calculation –> will contain the final hash value.
message the remaining message to be signed. The buffer must be a multiple of 64 s.t. message padding can be done by this function directly.
remaining_length the number of remaining bytes within "message"
total_length the total number of bytes signed
(total_length - remaining_length) should already been processed using sha1_process_message or sha1_process_block. (total_length - remaining_length) must be a multiple of 64!!
Definition at line 158 of file sha1.c.
References sha1_process_block(), and temp.
Referenced by cprng_one_way_func(), and sha1_hash().
void sha1_state_to_bigint (HASH_SHA1 * state, word_t * result)
Converts the given hash (state) to a big integer.
Parameters
state the hash to convert
result the big integer memory to use (make sure it is big enough)
Definition at line 240 of file sha1.c.
References HASH_SHA1_::H0, HASH_SHA1_::H1, HASH_SHA1_::H2, HASH_SHA1_::H3, and HASH_SHA1_::H4.
Referenced by sha1_hash().
void sha1_state_to_byte_array (HASH_SHA1 * state, uint8_t * message)
Converts the resulted hash state to a uint8_t* message.
Parameters
state
message
Definition at line 211 of file sha1.c.
References HASH_SHA1_::H0, HASH_SHA1_::H1, HASH_SHA1_::H2, HASH_SHA1_::H3, and HASH_SHA1_::H4.
Referenced by cprng_one_way_func().
Variable Documentation
const uint32_t H0_ROM = 0x67452301
Definition at line 41 of file sha1.c.
Referenced by sha1_init_state().
const uint32_t H1_ROM = 0xEFCDAB89
Definition at line 42 of file sha1.c.
Referenced by sha1_init_state().
const uint32_t H2_ROM = 0x98BADCFE
Definition at line 43 of file sha1.c.
Referenced by sha1_init_state().
const uint32_t H3_ROM = 0x10325476
Definition at line 44 of file sha1.c.
Referenced by sha1_init_state().
const uint32_t H4_ROM = 0xC3D2E1F0
Definition at line 45 of file sha1.c.
Referenced by sha1_init_state().