Pairings: /home/work/workspace/bipair_in_c/src/hash/sha2_small_common.c File Reference
sha2_small_common.c File Reference
#include <stdint.h>
#include <string.h>
#include "hash/sha2_small_common.h"
Macros
#define LITTLE_ENDIAN
#define CH(x, y, z) (((x)&(y)) ^ ((~(x))&(z)))
#define MAJ(x, y, z) (((x)&(y)) ^ ((x)&(z)) ^ ((y)&(z)))
#define SIGMA_0(x) (rotr32((x), 2) ^ rotr32((x),13) ^ rotl32((x),10))
#define SIGMA_1(x) (rotr32((x), 6) ^ rotr32((x),11) ^ rotl32((x),7))
#define SIGMA_a(x) (rotr32((x), 7) ^ rotl32((x),14) ^ ((x)>>3))
#define SIGMA_b(x) (rotl32((x),15) ^ rotl32((x),13) ^ ((x)>>10))
Functions
static uint32_t rotr32 (uint32_t x, uint8_t n)
rotate x right by n positions
static uint32_t rotl32 (uint32_t x, uint8_t n)
static void load_endian32_changed (uint8_t *dest, uint8_t *src, uint16_t words)
void sha2_small_common_nextBlock (sha2_small_common_ctx_t *state, const void *block)
block must be, 512, Bit = 64, Byte, long !!!
void sha2_small_common_lastBlock (sha2_small_common_ctx_t *state, const void *block, uint16_t length_b)
Variables
const uint32_t k []
Macro Definition Documentation
#define CH (x, y, z) (((x)&(y)) ^ ((~(x))&(z)))
Definition at line 52 of file sha2_small_common.c.
Referenced by sha2_small_common_nextBlock().
#define LITTLE_ENDIAN
Definition at line 24 of file sha2_small_common.c.
#define MAJ (x, y, z) (((x)&(y)) ^ ((x)&(z)) ^ ((y)&(z)))
Definition at line 53 of file sha2_small_common.c.
Referenced by sha2_small_common_nextBlock().
#define SIGMA_0 (x) (rotr32((x), 2) ^ rotr32((x),13) ^ rotl32((x),10))
Definition at line 55 of file sha2_small_common.c.
Referenced by sha2_small_common_nextBlock().
#define SIGMA_1 (x) (rotr32((x), 6) ^ rotr32((x),11) ^ rotl32((x),7))
Definition at line 56 of file sha2_small_common.c.
Referenced by sha2_small_common_nextBlock().
#define SIGMA_a (x) (rotr32((x), 7) ^ rotl32((x),14) ^ ((x)>>3))
Definition at line 57 of file sha2_small_common.c.
Referenced by sha2_small_common_nextBlock().
#define SIGMA_b (x) (rotl32((x),15) ^ rotl32((x),13) ^ ((x)>>10))
Definition at line 58 of file sha2_small_common.c.
Referenced by sha2_small_common_nextBlock().
Function Documentation
static void load_endian32_changed (uint8_t * dest, uint8_t * src, uint16_t words) static
Definition at line 73 of file sha2_small_common.c.
Referenced by sha2_small_common_nextBlock().
static uint32_t rotl32 (uint32_t x, uint8_t n) static
Definition at line 35 of file sha2_small_common.c.
static uint32_t rotr32 (uint32_t x, uint8_t n) static
rotate x right by n positions
Definition at line 30 of file sha2_small_common.c.
void sha2_small_common_lastBlock (sha2_small_common_ctx_t * state, const void * block, uint16_t length_b)
Definition at line 129 of file sha2_small_common.c.
References sha2_small_common_ctx_t::length, and sha2_small_common_nextBlock().
Referenced by sha256_lastBlock().
void sha2_small_common_nextBlock (sha2_small_common_ctx_t * state, const void * block)
block must be, 512, Bit = 64, Byte, long !!!
Definition at line 86 of file sha2_small_common.c.
References CH, sha2_small_common_ctx_t::h, k, sha2_small_common_ctx_t::length, load_endian32_changed(), MAJ, SIGMA_0, SIGMA_1, SIGMA_a, and SIGMA_b.
Referenced by sha256_nextBlock(), and sha2_small_common_lastBlock().
Variable Documentation
const uint32_t k[]
Initial value:
={
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
}
Definition at line 61 of file sha2_small_common.c.
Referenced by encapsulate_key(), and sha2_small_common_nextBlock().