Pairings: /home/work/workspace/bipair_in_c/src/hash/sha256.c File Reference
sha256.c File Reference
SHA-256 implementation.
#include <stdint.h>
#include <string.h>
#include "hash/sha2_small_common.h"
#include "hash/sha256.h"
Macros
#define LITTLE_ENDIAN
Functions
void sha256_init (sha256_ctx_t *state)
sh256_init initialises a sha256 context for hashing.
void sha256_nextBlock (sha256_ctx_t *state, const void *block)
update the context with a given block
void sha256_lastBlock (sha256_ctx_t *state, const void *block, uint16_t length_b)
finalize the context with the given block
void sha256 (void *dest, const void *msg, uint32_t length_b)
function to process the last block being hashed
void sha256_ctx2hash (void *dest, const sha256_ctx_t *state)
Variables
const uint32_t sha256_init_vector []
Detailed Description
SHA-256 implementation.
Author
Daniel Otte
Date
16.05.2006
License:
GPL
Definition in file sha256.c.
Macro Definition Documentation
#define LITTLE_ENDIAN
Definition at line 37 of file sha256.c.
Function Documentation
void sha256 (void * dest, const void * msg, uint32_t length_b)
function to process the last block being hashed
Parameters
state Pointer to the context in which this block should be processed.
block Pointer to the message wich should be hashed.
length is the length of only THIS block in BITS not in bytes! bits are big endian, meaning high bits come first. if you have a message with bits at the end, the byte must be padded with zeros
Definition at line 92 of file sha256.c.
References SHA256_BLOCK_BITS, sha256_ctx2hash(), sha256_init(), sha256_lastBlock(), and sha256_nextBlock().
Referenced by hash_id(), and hash_key().
void sha256_ctx2hash (void * dest, const sha256_ctx_t * state)
Definition at line 108 of file sha256.c.
References sha2_small_common_ctx_t::h.
Referenced by hwang_sign(), hwang_verify(), and sha256().
void sha256_init (sha256_ctx_t * state)
sh256_init initialises a sha256 context for hashing.
initialize a SHA-256 context
sh256_init c initialises the given sha256 context for hashing
Parameters
state pointer to a sha256 context
Returns
none
Definition at line 62 of file sha256.c.
References sha2_small_common_ctx_t::h, sha2_small_common_ctx_t::length, and sha256_init_vector.
Referenced by hwang_sign(), hwang_verify(), and sha256().
void sha256_lastBlock (sha256_ctx_t * state, const void * block, uint16_t length_b)
finalize the context with the given block
This function finalizes the SHA-256 hash context by processing the given block of variable length.
Parameters
state pointer to the SHA-256 hash context
block pointer to the block of fixed length (512 bit = 64 byte)
length_b the length of the block in bits
Definition at line 73 of file sha256.c.
References sha2_small_common_lastBlock().
Referenced by sha256().
void sha256_nextBlock (sha256_ctx_t * state, const void * block)
update the context with a given block
This function updates the SHA-256 hash context by processing the given block of fixed length.
Parameters
state pointer to the SHA-256 hash context
block pointer to the block of fixed length (512 bit = 64 byte)
Definition at line 68 of file sha256.c.
References sha2_small_common_nextBlock().
Referenced by hwang_sign(), hwang_verify(), sha256(), sha256_update_G1(), and sha256_update_GT().
Variable Documentation
const uint32_t sha256_init_vector[]
Initial value:
={
    0x6A09E667, 0xBB67AE85, 0x3C6EF372, 0xA54FF53A,
    0x510E527F, 0x9B05688C, 0x1F83D9AB, 0x5BE0CD19 }
Definition at line 49 of file sha256.c.
Referenced by sha256_init().