Pairings: /home/work/workspace/bipair_in_c/include/hash/sha2_small_common.h File Reference
sha2_small_common.h File Reference
Data Structures
struct sha2_small_common_ctx_t
Functions
void sha2_small_common_nextBlock (sha2_small_common_ctx_t *state, const void *block)
block must be, 512, Bit = 64, Byte, long !!!
void sha2_small_common_lastBlock (sha2_small_common_ctx_t *state, const void *block, uint16_t length_b)
Function Documentation
void sha2_small_common_lastBlock (sha2_small_common_ctx_t * state, const void * block, uint16_t length_b)
Definition at line 129 of file sha2_small_common.c.
References sha2_small_common_ctx_t::length, and sha2_small_common_nextBlock().
Referenced by sha256_lastBlock().
void sha2_small_common_nextBlock (sha2_small_common_ctx_t * state, const void * block)
block must be, 512, Bit = 64, Byte, long !!!
Definition at line 86 of file sha2_small_common.c.
References CH, sha2_small_common_ctx_t::h, k, sha2_small_common_ctx_t::length, load_endian32_changed(), MAJ, SIGMA_0, SIGMA_1, SIGMA_a, and SIGMA_b.
Referenced by sha256_nextBlock(), and sha2_small_common_lastBlock().