Pairings: /home/work/workspace/bipair_in_c/src/cortexm0/startup.c File Reference
startup.c File Reference
#include <stdint.h>
Functions
int main (void)
void Reset_Handler (void)
void NMI_Handler (void)
void Dummy_Handler (void)
void _endless_loop__ (void)
Variables
unsigned int __stack
unsigned int __erodata
unsigned int __data_start__
unsigned int __data_end__
unsigned int __bss_start__
unsigned int __bss_end__
Function Documentation
void _endless_loop__ (void)
Definition at line 145 of file startup.c.
void Dummy_Handler (void)
Definition at line 140 of file startup.c.
int main (void)
Definition at line 506 of file bench.c.
References assert_bi_equal(), assert_bi_equal_var(), assert_bytearr_equal(), assert_equal(), assert_true(), bi_add, bi_clear, bi_compare, bi_copy, bi_div3, bi_multiply, bi_one, bi_shift_right, bi_shift_right_one, bi_square, bi_subtract, BI_WORDS, bi_zero, decapsulate_key(), ecfp2_add_affine, ecfp2_add_proj, ecfp2_clear, ecfp2_copy, ecfp2_dbl_affine, ecfp2_dbl_proj, ecfp2_hash_to_point, ecfp2_mul, ecfp2_neg_affine, ecfp2_neg_proj, ecfp_add_affine, ecfp_add_proj, ecfp_clear, ecfp_copy, ecfp_dbl_affine, ecfp_dbl_proj, ecfp_hash_to_point, ecfp_mul, ecfp_neg_affine, ecfp_neg_proj, encapsulate_key(), fp12_add, fp12_clear, fp12_copy, fp12_dbl, fp12_exp, fp12_exp_cyclotomic, fp12_frobenius_map, fp12_hlv, fp12_inv, fp12_mul, fp12_neg, fp12_sqr, fp12_sub, fp2_add, fp2_clear, fp2_copy, fp2_dbl, fp2_exp, fp2_frobenius_map, fp2_hlv, fp2_inv, fp2_legendre, fp2_mul, fp2_neg, fp2_sqr, fp2_sqrt, fp2_sub, fp4_add, fp4_clear, fp4_copy, fp4_dbl, fp4_exp, fp4_frobenius_map, fp4_hlv, fp4_inv, fp4_mul, fp4_neg, fp4_sqr, fp4_sub, fp_add, fp_clear, fp_copy, fp_dbl, fp_exp, fp_hlv, fp_inv, fp_inv_n, fp_legendre, fp_mul, fp_mul_monty, fp_mul_monty_fips_std(), fp_mul_monty_std(), fp_mul_monty_var, fp_neg, fp_sqr, fp_sqrt, fp_sub, hash_id(), hwang_generate_usk(), hwang_init_parameters(), hwang_sign(), hwang_verify(), ecpoint_fp::infinity, ecpoint_fp_proj::infinity, ecpoint_fp2::infinity, ecpoint_fp2_proj::infinity, MONTY_PRIME_N0, MONTY_PRIME_R2, pbc_map_opt_ate, pbc_map_opt_ate_div, pbc_map_opt_ate_mul, PRIME_P, print(), print_value(), ecpoint_fp::x, ecpoint_fp_proj::x, ecpoint_fp2::x, ecpoint_fp2_proj::x, ecpoint_fp::y, ecpoint_fp_proj::y, ecpoint_fp2::y, ecpoint_fp2_proj::y, ecpoint_fp_proj::z, and ecpoint_fp2_proj::z.
Referenced by Reset_Handler().
void NMI_Handler (void)
Definition at line 48 of file startup.c.
References __stack, and Reset_Handler().
void Reset_Handler (void)
Definition at line 123 of file startup.c.
References __bss_end__, __bss_start__, __data_end__, __data_start__, __erodata, and main().
Referenced by NMI_Handler().
Variable Documentation
unsigned int __bss_end__
Referenced by Reset_Handler().
unsigned int __bss_start__
Referenced by Reset_Handler().
unsigned int __data_end__
Referenced by Reset_Handler().
unsigned int __data_start__
Referenced by Reset_Handler().
unsigned int __erodata
Referenced by Reset_Handler().
unsigned int __stack
Referenced by NMI_Handler().