Pairings: /home/work/workspace/bipair_in_c/test/test_bbkem.c File Reference
test_bbkem.c File Reference
#include "ibe/bbkem.h"
Functions
int main (void)
Function Documentation
int main (void)
Definition at line 37 of file test_bbkem.c.
References assert_bytearr_equal(), decapsulate_key(), and encapsulate_key().