Pairings: /home/work/workspace/bipair_in_c/src/util.c File Reference
util.c File Reference
#include "util.h"
#include "config.h"
#include <string.h>
#include <stdio.h>
Macros
#define UART_BASE 0x40000000
#define TX_OFFSET 20
#define TCTL_OFFSET 0x000004
#define CYCLE_COUNT_ADDR 0xE000ED80
Functions
void print (const char *msg)
Prints a message.
char * print_word (char *buffer, const word_t w)
Prints a processor word to a string.
void print_value (const word_t *value, const length_t len)
Prints a multi-precision integer of defined length.
void print_bytes (const byte *value, const length_t len)
Prints an array of bytes of arbitrary length.
int compare_bytes (const byte *a, const byte *b, const length_t len)
Compares two byte arrays of defined length.
unsigned long long get_cycles ()
Determines the processor's current cycle.
Variables
const char hex_lookup []
Macro Definition Documentation
#define CYCLE_COUNT_ADDR 0xE000ED80
Definition at line 47 of file util.c.
Referenced by get_cycles().
#define TCTL_OFFSET 0x000004
Definition at line 46 of file util.c.
Referenced by print().
#define TX_OFFSET 20
Definition at line 45 of file util.c.
Referenced by print().
#define UART_BASE 0x40000000
Definition at line 44 of file util.c.
Referenced by print().
Function Documentation
int compare_bytes (const byte * a, const byte * b, const length_t len)
Compares two byte arrays of defined length.
Parameters
a the first array to be compared
b the second array to be compared
len the length of the arrays
Returns
0 if equal, 1 if the first is larger, -1 otherwise
Definition at line 152 of file util.c.
Referenced by assert_bytearr_equal().
unsigned long long get_cycles (void)
Determines the processor's current cycle.
Returns
the number of the current cycle
Definition at line 170 of file util.c.
References CYCLE_COUNT_ADDR.
Referenced by benchmark_start(), and benchmark_stop().
void print (const char * msg)
Prints a message.
Parameters
msg the message to be printed
Definition at line 57 of file util.c.
References TCTL_OFFSET, TX_OFFSET, and UART_BASE.
Referenced by assert_bi_equal(), assert_bi_equal_var(), assert_bytearr_equal(), assert_equal(), assert_true(), benchmark_print(), generateMultiplyKaratsubaFull::highPart(), generateMultiplyKaratsuba::highPart(), hwang_generate_usk(), hwang_init_parameters(), hwang_sign(), generateMultiplyKaratsuba::lowPart(), generateMultiplyKaratsubaFull::lowPart(), main(), generateMultiplyKaratsuba::middlePart(), generateMultiplyKaratsubaFull::middlePart(), print_bytes(), print_value(), generateMultiplyKaratsuba::propagateAccumulator(), and generateMultiplyKaratsubaFull::propagateAccumulator().
void print_bytes (const byte * value, const length_t len)
Prints an array of bytes of arbitrary length.
Parameters
value the byte array to be printed
len the length of the array
Definition at line 133 of file util.c.
References hex_lookup, and print().
Referenced by assert_bytearr_equal().
void print_value (const word_t * value, const length_t len)
Prints a multi-precision integer of defined length.
Parameters
value the value to be printed
len the number of words of the value
Definition at line 108 of file util.c.
References print(), print_word(), and WORDS_PER_BITS.
Referenced by assert_bi_equal(), assert_bi_equal_var(), assert_equal(), hash_update_G1(), and main().
char* print_word (char * buffer, const word_t w)
Prints a processor word to a string.
Parameters
buffer the buffer that is written to
w the processor word
Returns
a pointer to the buffer
Definition at line 82 of file util.c.
References hex_lookup.
Referenced by print_value().
Variable Documentation
const char hex_lookup[]
Initial value:
= {'0', '1', '2', '3',
                     '4', '5', '6', '7',
                     '8', '9', 'a', 'b',
                     'c', 'd', 'e', 'f'}
Definition at line 39 of file util.c.
Referenced by print_bytes(), and print_word().