PAIRINGS_IN_C: src/ibe/bbkem.c File Reference
bbkem.c File Reference
#include "ibe/bbkem.h"
#include "ec/ec.h"
#include "param.h"
#include "rand.h"
#include "fp/fp.h"
#include "fp/fp12.h"
#include "hash/hashing.h"
#include "pbc/pbc.h"
#include "bigint/bi.h"
#include "util.h"
Functions
void generate_params (bbkem_msk *msk, bbkem_public *params)
Generation of the master secret key and the public parameters for the BB1 IBE key encapsulation mechanism.
void derive_private_key (bbkem_pk *upk, bbkem_msk *msk, bbkem_public *params, const char *id)
Derives a user private key to be used in the BB1 IBE key encapsulation mechanism from the master secret key, the public parameters, and the identity string.
void encapsulate_key (byte *key, bbkem_ciphertext *cipher, bbkem_public *params, const char *id)
Encapsulation routine of the BB1 IBE KEM.
void decapsulate_key (byte *key, bbkem_ciphertext *cipher, bbkem_public *params, bbkem_pk *upk)
Decapsulation routine of the BB1 IBE KEM.
Function Documentation
void decapsulate_key (byte * key, bbkem_ciphertext * cipher, bbkem_public * params, bbkem_pk * upk)
Decapsulation routine of the BB1 IBE KEM.
Takes the identity's private key and the received ciphertext to compute the session key to be used. Note that the current implementation does not use the identity string, but always takes the same private key.
Parameters
key the resulting session key
cipher the ciphertext to be decrypted
id the identity string used
Definition at line 157 of file bbkem.c.
References hash_key().
Referenced by main().
void derive_private_key (bbkem_pk * upk, bbkem_msk * msk, bbkem_public * params, const char * id)
Derives a user private key to be used in the BB1 IBE key encapsulation mechanism from the master secret key, the public parameters, and the identity string.
Parameters
upk the generated user private key
msk the master secret key
params the public parameters
id the identity string
Definition at line 86 of file bbkem.c.
References cprng_get_bytes(), and hash_id().
Referenced by main().
void encapsulate_key (byte * key, bbkem_ciphertext * cipher, bbkem_public * params, const char * id)
Encapsulation routine of the BB1 IBE KEM.
Uses the recipient's identity string to establish a session key and a ciphertext decryptable only by the intended recipient.
Parameters
key the resulting session key
cipher the resulting ciphertext
id the identity string of the recipient
Definition at line 115 of file bbkem.c.
References cprng_get_bytes(), hash_id(), and hash_key().
Referenced by main().
void generate_params (bbkem_msk * msk, bbkem_public * params)
Generation of the master secret key and the public parameters for the BB1 IBE key encapsulation mechanism.
Parameters
msk the master secret key
params the public parameters
Definition at line 52 of file bbkem.c.
References cprng_get_bytes(), print(), and print_value().
Referenced by main().