PAIRINGS_IN_C: src/gss/gss_hwang.c File Reference
gss_hwang.c File Reference
#include "types.h"
#include "rand.h"
#include "fp/fp.h"
#include "bigint/bi.h"
#include "ec/ec.h"
#include "util.h"
#include "pbc/pbc.h"
#include "fp/fp12.h"
#include "gss/gss_hwang.h"
#include "hash/hash_function.h"
#include <string.h>
Macros
#define DEBUG_PRINT 1
Functions
sbyte hwang_sign (hwang_signature_ptr sig, hwang_public_parameters_ptr data, hwang_signing_key_ptr usk)
Generates a signature according to the scheme of HWANG.
void hwang_init_parameters (hwang_public_parameters_ptr data)
Initializes the public parameters, the master issuing key (MIK), the master opening key (MOK), and the master linking key (MLK).
void hwang_generate_usk (hwang_signing_key_ptr usk, hwang_public_parameters_ptr data)
Generates a tuple (x, y, z, A) — with x, y, z {Z}_p^* and A {G}_1 — that acts as a user's signing key.
sbyte hwang_verify (hwang_public_parameters_ptr data, hwang_signature_ptr sig)
Verify a group signature.
Macro Definition Documentation
#define DEBUG_PRINT 1
Definition at line 47 of file gss_hwang.c.
Function Documentation
void hwang_generate_usk (hwang_signing_key_ptr usk, hwang_public_parameters_ptr data)
Generates a tuple (x, y, z, A) — with x, y, z {Z}_p^* and A {G}_1 — that acts as a user's signing key.
Parameters
usk [out] the generated signing key for one user.
data [in] the public parameters.
Definition at line 287 of file gss_hwang.c.
References cprng_get_bytes(), and print().
Referenced by main().
void hwang_init_parameters (hwang_public_parameters_ptr data)
Initializes the public parameters, the master issuing key (MIK), the master opening key (MOK), and the master linking key (MLK).
Definition at line 225 of file gss_hwang.c.
References bi_copy_var_std(), cprng_get_bytes(), and print().
Referenced by main().
sbyte hwang_sign (hwang_signature_ptr sig, hwang_public_parameters_ptr data, hwang_signing_key_ptr usk)
Generates a signature according to the scheme of HWANG.
Parameters
sig [out] computed signature.
data [in] public data of HWANG scheme.
usk [in] user secret key to generate a valid signature.
Returns
0 on success; -1 on ERROR;
Definition at line 57 of file gss_hwang.c.
References bi_clear_var_std(), bi_copy_var_std(), cprng_get_bytes(), hash_update_G1(), hash_update_GT(), and print().
Referenced by main().
sbyte hwang_verify (hwang_public_parameters_ptr data, hwang_signature_ptr sig)
Verify a group signature.
Parameters
data the parameters of the group-signature scheme.
sig the generated signature to be verified.
Returns
1 if the signature is VALID; -1 otherwise.
Definition at line 341 of file gss_hwang.c.
References bi_clear_var_std(), bi_copy_var_std(), fp12_exp_std(), fp12_mul_std(), hash_update_G1(), and hash_update_GT().
Referenced by main().