/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class iaik_at_groupsignature_MainActivity */

#ifndef _Included_iaik_at_groupsignature_MainActivity
#define _Included_iaik_at_groupsignature_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef iaik_at_groupsignature_MainActivity_BIND_ABOVE_CLIENT
#define iaik_at_groupsignature_MainActivity_BIND_ABOVE_CLIENT 8L
#undef iaik_at_groupsignature_MainActivity_BIND_ADJUST_WITH_ACTIVITY
#define iaik_at_groupsignature_MainActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef iaik_at_groupsignature_MainActivity_BIND_ALLOW_OOM_MANAGEMENT
#define iaik_at_groupsignature_MainActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef iaik_at_groupsignature_MainActivity_BIND_AUTO_CREATE
#define iaik_at_groupsignature_MainActivity_BIND_AUTO_CREATE 1L
#undef iaik_at_groupsignature_MainActivity_BIND_DEBUG_UNBIND
#define iaik_at_groupsignature_MainActivity_BIND_DEBUG_UNBIND 2L
#undef iaik_at_groupsignature_MainActivity_BIND_IMPORTANT
#define iaik_at_groupsignature_MainActivity_BIND_IMPORTANT 64L
#undef iaik_at_groupsignature_MainActivity_BIND_NOT_FOREGROUND
#define iaik_at_groupsignature_MainActivity_BIND_NOT_FOREGROUND 4L
#undef iaik_at_groupsignature_MainActivity_BIND_WAIVE_PRIORITY
#define iaik_at_groupsignature_MainActivity_BIND_WAIVE_PRIORITY 32L
#undef iaik_at_groupsignature_MainActivity_CONTEXT_IGNORE_SECURITY
#define iaik_at_groupsignature_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef iaik_at_groupsignature_MainActivity_CONTEXT_INCLUDE_CODE
#define iaik_at_groupsignature_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef iaik_at_groupsignature_MainActivity_CONTEXT_RESTRICTED
#define iaik_at_groupsignature_MainActivity_CONTEXT_RESTRICTED 4L
#undef iaik_at_groupsignature_MainActivity_MODE_APPEND
#define iaik_at_groupsignature_MainActivity_MODE_APPEND 32768L
#undef iaik_at_groupsignature_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define iaik_at_groupsignature_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef iaik_at_groupsignature_MainActivity_MODE_MULTI_PROCESS
#define iaik_at_groupsignature_MainActivity_MODE_MULTI_PROCESS 4L
#undef iaik_at_groupsignature_MainActivity_MODE_PRIVATE
#define iaik_at_groupsignature_MainActivity_MODE_PRIVATE 0L
#undef iaik_at_groupsignature_MainActivity_MODE_WORLD_READABLE
#define iaik_at_groupsignature_MainActivity_MODE_WORLD_READABLE 1L
#undef iaik_at_groupsignature_MainActivity_MODE_WORLD_WRITEABLE
#define iaik_at_groupsignature_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef iaik_at_groupsignature_MainActivity_DEFAULT_KEYS_DIALER
#define iaik_at_groupsignature_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef iaik_at_groupsignature_MainActivity_DEFAULT_KEYS_DISABLE
#define iaik_at_groupsignature_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef iaik_at_groupsignature_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define iaik_at_groupsignature_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef iaik_at_groupsignature_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define iaik_at_groupsignature_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef iaik_at_groupsignature_MainActivity_DEFAULT_KEYS_SHORTCUT
#define iaik_at_groupsignature_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef iaik_at_groupsignature_MainActivity_RESULT_CANCELED
#define iaik_at_groupsignature_MainActivity_RESULT_CANCELED 0L
#undef iaik_at_groupsignature_MainActivity_RESULT_FIRST_USER
#define iaik_at_groupsignature_MainActivity_RESULT_FIRST_USER 1L
#undef iaik_at_groupsignature_MainActivity_RESULT_OK
#define iaik_at_groupsignature_MainActivity_RESULT_OK -1L
#undef iaik_at_groupsignature_MainActivity_HONEYCOMB
#define iaik_at_groupsignature_MainActivity_HONEYCOMB 11L
#undef iaik_at_groupsignature_MainActivity_MSG_REALLY_STOPPED
#define iaik_at_groupsignature_MainActivity_MSG_REALLY_STOPPED 1L
#undef iaik_at_groupsignature_MainActivity_MSG_RESUME_PENDING
#define iaik_at_groupsignature_MainActivity_MSG_RESUME_PENDING 2L
/*
 * Class:     iaik_at_groupsignature_MainActivity
 * Method:    sign
 * Signature: (Ljava/lang/String;Liaik/at/groupsignature/GroupPublicKey;Liaik/at/groupsignature/GroupSecretKey;)Liaik/at/groupsignature/SdhSignature;
 */
JNIEXPORT jobject JNICALL Java_iaik_at_groupsignature_MainActivity_sign
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     iaik_at_groupsignature_MainActivity
 * Method:    verify
 * Signature: (Ljava/lang/String;Liaik/at/groupsignature/GroupPublicKey;Liaik/at/groupsignature/SdhSignature;)I
 */
JNIEXPORT jint JNICALL Java_iaik_at_groupsignature_MainActivity_verify
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     iaik_at_groupsignature_MainActivity
 * Method:    open
 * Signature: (Liaik/at/groupsignature/GroupMasterSecretKey;Liaik/at/groupsignature/SdhSignature;)Liaik/at/groupsignature/EcPoint_Fp;
 */
JNIEXPORT jobject JNICALL Java_iaik_at_groupsignature_MainActivity_open
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
